### ISSUE TITLE
Download all languages for a namespace

### ISSUE THREAD

**Issue by danni** [locize/locize-cli#10]
A project only requires a single namespace. It would be good to be able to download all language files for a namespace.

**Comment by danni** [comment]
We have a product split across a number of repositories/build processes. These are run as one locize project shared overview. Each component is associated with a namespace, plus shared namespaces for common items that appear throughout the product (we deal with statistical metrics).

It would be ideal when downloading resources to only download the required namespaces for that component.

**Comment by adrai** [comment]
Ok, understand... will look into it ;-)

**Comment by adrai** [comment]
Done :-)
You can try with v4.3.0
with something like this: `locize download --format json --namespace ara`

**Comment by danni** [comment]
Tested and working. Thanks.

It would be super cool if you could pass `--namespace` twice.

**Comment by adrai** [comment]
Nice to hear.
Sorry, but what do you mean by “passing twice”?

**Comment by adrai** [comment]
perhaps: —namespace ns1,ns2,ns3    ?

**Comment by adrai** [comment]
Would you like to try with `--namespace ns1,ns2,ns3` with version 4.3.1?

**Comment by danni** [comment]
Works great. Thanks!
