### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by dolie** [locize/locize-cli#100]
## 🐛 Bug Report

`Locize-cli` uses `rimraf@3.0.2` which is a deprecated dependency which includes other deprecated dependencies... :
<img width="310" alt="image" src="https://github.com/user-attachments/assets/59b2d368-8f6a-4307-a5d5-db0ac8c208cb">
<img width="596" alt="image" src="https://github.com/user-attachments/assets/9d0cc4b3-149e-438a-bc0c-99bb6b597c0e">
<img width="507" alt="image" src="https://github.com/user-attachments/assets/9d6f80c1-51dc-433c-95f9-c41480699740">
<img width="490" alt="image" src="https://github.com/user-attachments/assets/8292be53-dae2-4dc6-8919-79036616adad">
<img width="952" alt="image" src="https://github.com/user-attachments/assets/b0d3b3d8-d7d4-4d4f-bed8-55034fd4b618">

## To Reproduce

Install last version of `locize-cli`

## Expected behavior

`Locize-cli` uses up-to-date dependencies, so it does not introduce security or performance issues.

## Your Environment

- *runtime version*: node lts
- *module version*: lts

**Comment by adrai** [comment]
We still use(d) these old dependencies because some customer still use older Node.js versions.
We're planning to create a new major version that will drop support for some older Node.js version.

**Comment by adrai** [comment]
fyi: we just released a minor version to address at least the rimraf warning: [v8.3.0](https://github.com/locize/locize-cli/releases/tag/v8.3.0)
