### ISSUE TITLE
empty strings missing from download

### ISSUE THREAD

**Issue by benma** [locize/locize-cli#11]
Hi

Inside locize.io, when I download a nested/flat json, my empty strings are preserved, e.g. `{ "welcome.title: "" }`.

When I download via `locize download` (or use the [locize API directly](https://docs.locize.com/integration/api#fetch-namespace-resources)), the result does not contain those keys anymore.

What gives?

**Comment by adrai** [comment]
Hi @benma!
You're right, there is a mismatch between cli download (from cdn) and locize client download (database)
We are going to fix the client. (empty strings will be removed there too)
Is this ok for you?
If this is a problem we will introduce a new project setting to preserve empty strings everywhere.
Let me know.
Thanks

**Comment by adrai** [comment]
Ok, we are going to introduce a new project settings.... ;-)

**Comment by adrai** [comment]
it will look more ore less like this: 
![image](https://user-images.githubusercontent.com/1086194/46956079-ae21fb80-d094-11e8-9137-2a1412679c85.png)

**Comment by adrai** [comment]
The feature has been released... 😉

**Comment by benma** [comment]
Thanks a lot, awesome!
