### ISSUE TITLE
force overwrite existing reference language values

### ISSUE THREAD

**Issue by benma** [locize/locize-cli#12]
Hi

I am worried that occasionally, the normal workflow would be broken and the reference language files would be changed in our repo, and not inside of locize. When that happens, I'd like to basically force push the repo files, as it sounds very hard to find the exact difference and manually fix the entries in locize.

Right now for example I got an old `en` version on locize while integrating the workflow, and in the meantime the repo file has changed. How to reset?

I am basically looking for `locize sync`, which also overwrites existing key values.

How to do that without deleting and restarting the whole project?

Thanks

**Comment by benma** [comment]
Sorry for the noise, discovered `--update-values true`.

**Comment by jamuhl** [comment]
Awesome you already found it - if it wouldn't have been there we would have added it asap.
