### ISSUE TITLE
bug: object converted to array!

### ISSUE THREAD

**Issue by benma** [locize/locize-cli#13]
```json
{ "foo": { "100": "bar" } }
```

When imported and exported from locize, this becomes:

```
{ "foo": [ null, null, null, null, .........., "bar" ] }
```

With 99 `null` entries. Expected is that the exported file is the same as the original.

**Comment by benma** [comment]
Also, on `locize sync`, if there is an element like `"10000": "foo"`, it is not even added to locize it seems.

**Comment by jamuhl** [comment]
The reason for this is that numbers are considered to be index in array (that is a normal behaviour you get when using flatten/unflatten)

```js
{
  "key": ['a', 'b']
}

will become

{
  "key.0": 'a',
  "key.1": 'b'
}
```

to avoid this behavior just add one key not being a numeral like:

```js
{ "foo": { "100": "bar", "avoidIt": " " } }

results in and will get converted back correctly

{
  "key.100": 'bar',
  "key.avoidIt": ' '
}
```

10000 is not supported as we check for the array length...and some point we say there must be an error -> no one fills a translation array with over 10000 items.

**Comment by benma** [comment]
I see, so flat and unflat are not proper inverses of each other :( Thanks, I will work around it.

**Comment by jamuhl** [comment]
not a 100% but that is a tradeoff: https://www.npmjs.com/package/flat

we at least extended it to make it an object if there is one non numeral value. In most cases that works fine eg having something like:

```js
{
  errors: {
    default: 'something went wrong',
    400: 'page not found',
    ....
  }
}
```
