### ISSUE TITLE
Response error detection is shaky

### ISSUE THREAD

**Issue by RomanSek** [locize/locize-cli#16]
It's possible to create translation file that can't be downloaded using `locize download`. Program will fail download when translation namespace contains "message" or "errorMessage" key with any value.

I think it's caused by [this line](https://github.com/locize/locize-cli/blob/d774365d574d41b9410c6c59830c5ca84fd6dfb8/download.js#L16), but this logic is repeated in other places.

How to reproduce:
* Create project in locize.
* Create namespace with "message" or "errorMessage" key with value "WAT?"
* Use locize-cli to download all translations: `locize download --project-id ${LOCIZE_PROJECT_ID}`

What happens:
* locize-cli stops downloading translations and returns non-zero exit code
* locize-cli gives user error message (it's the value of the "message" or "errorMessage" key). In this case it's "WAT?"

What should happen:
* locize-cli should download all translations
* locize-cli should return 0 exit code

**Comment by adrai** [comment]
very interesting... will look at it asap

**Comment by adrai** [comment]
Can you try it again with v4.3.4 ?
Sorry for the inconvenience.

**Comment by RomanSek** [comment]
It works. Thanks for quick response.
