### ISSUE TITLE
Response handling in child_process when using locize sync.

### ISSUE THREAD

**Issue by linus-publit** [locize/locize-cli#17]
We are trying to set up a script in our package to do a i18next parse, followed by a `locize sync`. In doing so we want to be able to detect errors as well as outputting the success, but can't seem to get any. 

At first we thought it might be a sync problem where the exec wouldn't have time to finish. But making it async didn't solve the problem. `stdout` and `stderror` are still null. 

This is the locize part of the script:
```
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function main() {
  const { stdout, stderr } = await exec( 
    `locize sync` +
    `--api-key [API_KEY]` + 
    `--project-id [PROJECT_ID]` + 
    `--format json`
  );

    if (stderr) {
    console.error(`error: ${stderr}`);
  }
  console.log(`success: ${stdout}`);
}

main();
```
In our test case we just passed `--api-key 1 --project-id 2`, expecting `stderr` to return `Reference language not found` since that's what it does when running the command straight in the terminal.

Any suggestions?

**Comment by adrai** [comment]
Hehe... can happen to everyone...
btw: if you’re using javascript anyway... take a look at require(‘locize-cli/sync’)
