### ISSUE TITLE
Sync with .po files does not work

### ISSUE THREAD

**Issue by balsagoth** [locize/locize-cli#18]
I'm trying to use this tool with gettext po files, but this is not working.

The sync tool has a weird behavior. I already lost some translations, and my billing skyrocketed.

To reproduce the problem get a po file and a bunch of untranslated keys. The sync tool will add them all. Without changing anything, the second time the sync tool runs, it will delete all keys and add them all again. Somewhere in between all untranslated keys on locize disappear. 

<img width="553" alt="screenshot 2018-12-03 17 13 30" src="https://user-images.githubusercontent.com/183991/49389662-c8846700-f71e-11e8-931b-fcccbc8cc3ea.png">

As you can see on the screenshot, the sync tool removes and adds keys without any changes on locize nor the po file.

**Comment by adrai** [comment]
Will look at it as soon as possible...

**Comment by adrai** [comment]
I can't reproduce it with, can you say which arguments you use for the locize sync command?
Is it possible you have not published the files? (i.e. via auto-publish)

**Comment by balsagoth** [comment]
`locize sync --project-id XXXXXX --api-key XXXXX --format po`

I have this settings.

![screenshot 2018-12-03 18 06 41](https://user-images.githubusercontent.com/183991/49392467-71829000-f726-11e8-9734-c621ddd286ba.png)
![screenshot 2018-12-03 18 06 47](https://user-images.githubusercontent.com/183991/49392468-721b2680-f726-11e8-8372-98bb351bb414.png)

I can't do more tests because this is increasing our costs. There is any change to stop billing on this project until we figure what is wrong?

**Comment by adrai** [comment]
Thanks for the information.
We will try to reproduce it.
About the costs... no worry, we will find a solution... (will send you a proposal afterwards)

**Comment by adrai** [comment]
btw: with the argument `--dry true` you can see if it would change something (without actually generating modifications on locize)

**Comment by balsagoth** [comment]
Thanks for the quick bugfix.
