### ISSUE TITLE
Sync command is very dangerous. Turn it safer

### ISSUE THREAD

**Issue by balsagoth** [locize/locize-cli#19]
I think you should turn sync command a bit safer.
If by accident we execute sync command out of languages directory, all directories on the current path will be deleted with `rm -rf`, so not recoverable. 
I made that mistake, fortunately, inside of a project folder without any uncommitted code. But it could be much dangerous, for example inside home dir.
There are many options available to avoid this.

- Require a path argument with the path of the languages dir 
- Require a confirmation when `rm` is about to delete anything.
- Do `rm` with `-i`

**Comment by adrai** [comment]
Thanks for your input, have to think about it...
Another proposal could be to just delete folders matching a language code not present in the project (not all folders)

**Comment by adrai** [comment]
With version 4.5.4 I first check if the folder to remove is a "language" folder...

**Comment by balsagoth** [comment]
Thanks @adrai!
