### ISSUE TITLE
add a command to normalize the json files

### ISSUE THREAD

**Issue by benma** [locize/locize-cli#20]
Hi

`locize download` fetched json files from locize in a normalized format (indentation, alphabetized, etc.).

When adding keys for translations into the files manually, it would be nice if I could run something like `locize normalize` or `locize format` to reformat the json. The reason is that downloading the locize files and committing them to the repo produce needlessly big diffs (reordering).

Bonus if there would be a `--dry-run` flag which exits with 0 or 1 depending on whether the files need formatting at all (to include it into our CI).

**Comment by adrai** [comment]
Hi @benma !

Just released a new version: v4.6.0 (https://github.com/locize/locize-cli#format-local-files-ie-in-combination-with-download-command)

For your usecase should be able to call `locize format` (defaults to json format) or `locize format --format flat` (if you wish to enforce a flat json)

By adding `--dry true` it should behave the way you described it...

I hope this is what you were looking for. ;-)

**Comment by benma** [comment]
Thanks a lot for the quick response and action! :clap:  Integrated this successfully into our workflow here: https://github.com/digitalbitbox/bitbox-wallet-app/pull/265/

**Comment by adrai** [comment]
👍
