### ISSUE TITLE
Sync: namespace(s) option not respected unless reference-language-only=false

### ISSUE THREAD

**Issue by joeholdcroft** [locize/locize-cli#21]
When running the sync command with the default setting for the `reference-language-only` option (true), the code does not read the `namespace` and `namespaces` option, so it's not possible to filter to only certain namespaces while also using the reference language only option.

Working on a PR for this now.

**Comment by adrai** [comment]
awesome, thx for the fix

**Comment by adrai** [comment]
released with v4.6.1
