### ISSUE TITLE
An option to not delete keys from locize during sync

### ISSUE THREAD

**Issue by rpominov** [locize/locize-cli#24]
From documentation:

> if you have less keys (you have deleted some keys) in your local namespace it will remove them in locize too

This can be a problem when different people work in their branches and run `sync`. They may delete each other keys, because person A doesn't have keys from person B's branch and vice versa.

Is it possible to add an option to run sync without deletion of missing keys?

**Comment by adrai** [comment]
Nice idea!

There is now an additional parameter --skip-delete true (default is false) in v4.7.0

**Comment by rpominov** [comment]
That was fast! Thanks a lot!
