### ISSUE TITLE
The `--skip-delete` option doesn't work

### ISSUE THREAD

**Issue by rpominov** [locize/locize-cli#25]
The `--skip-delete` option that you've added for #24 doesn't seem to work. It says in console "skipping the removal of 1 keys in en/common..." but the key still gets deleted.

**Comment by rpominov** [comment]
Waiting on https://github.com/locize/locize-cli/issues/25

**Comment by adrai** [comment]
You are right!
I'm so sorry... 
Can you try with v4.7.1 ?

**Comment by rpominov** [comment]
Works fine with `v4.7.1`. Thanks!
