### ISSUE TITLE
Localization key sorting during sync

### ISSUE THREAD

**Issue by butchyyyy** [locize/locize-cli#28]
When syncing reference language from project to locize.com via sync command. The sync process reorders all the translation keys in the file alphabetically.
Since we try to organize the translations inside the file in logical order, it would be really nice to suppress this functionality via configuration (command line argument).

**Comment by adrai** [comment]
It’s not (only) the cli, the published files in locize are sorted alphabetically too.

**Comment by adrai** [comment]
closing this... feel free to reopen if you have still questions
