### ISSUE TITLE
Plural forms for downloaded PO-files strings misbehavior

### ISSUE THREAD

**Issue by mrkv** [locize/locize-cli#29]
Using web interface (locize.io) for downloading translations we get proper result:

```
msgid "tied with %{count} other"
msgid_plural "tied with %{count} other"
msgstr[0] "à égalité avec %{count} other"
msgstr[1] "à égalité avec %{count} others"
```

Using Locize CLI "download" method, we get strings only in plural form:

```
msgid "tied with %{count} other"
msgstr "à égalité avec %{count} others"
```

Switching on any other format from GetText, we get proper result too:

```
{
  "tied with %{count} other": "à égalité avec %{count} other",
  "tied with %{count} other_plural": "à égalité avec %{count} others"
}
```

We use Locize CLI, v4.8.0.

**Comment by adrai** [comment]
Thanks for reporting....
strange have to investigate...
will let you know asap

**Comment by adrai** [comment]
Short question: Is it possible you are using `locize download --format gettext` instead of `locize download --format gettext_i18next`?

**Comment by mrkv** [comment]
We've used `locize download --format po`, following the [description](https://github.com/locize/locize-cli#step-3-execute).

Using `locize download --format gettext` or `locize download --format gettext_i18next` provides right result. Thanks!

Probably, Readme should be updated on all available formats.
And actually I don't clearly understand why PO and GETTEXT formats has such differences.

**Comment by adrai** [comment]
gettext_i18next was so far a hidden feature (because original gettext has no handling for plural rules)...
With the new version 4.8.1 `--format gettext` or `--format po` should also work.

**Comment by mrkv** [comment]
Thank you for the quick reply!
And have a nice day.

**Comment by adrai** [comment]
Thanks, you too ;-)
