### ISSUE TITLE
Download in alphabetical order

### ISSUE THREAD

**Issue by psavard** [locize/locize-cli#3]
When I use the "Export JSON Flat" option directly in the namespace of locize.io, the file is exported in alphabetical order and this very useful.

Is it possible to have the same result with locize-cli?

If it's not supported now, is it something doable in the near future?

Thank you

**Comment by adrai** [comment]
done in v3.3.1
May I ask for which project you are working on locize? projectId?

**Comment by psavard** [comment]
e1712866-dfc7-4677-8cf6-b133d3a04cd7
