### ISSUE TITLE
Plural forms for downloaded and uploading PO-files.

### ISSUE THREAD

**Issue by RomaKozeko** [locize/locize-cli#30]
Hello!
I use locize-cli to synchronize localization files with locize.
In the project we use the PO file format.
Here is an example of a valid key.

```
msgid "tied with% {count} other% {test_one} test"
msgid_plural "tied with% {count} others% {test_one} test"
msgstr [0] "à égalité avec% {count} other% {test_one} test"
msgstr [1] "à égalité avec% {count} others% {test_one} test"
```

After locize sync --api-key api_key --project-id project_id --format po
we see the following fields in locize:

```
"tied with% {count} other% {test_one} test": "à égalité avec% {count} other% {test_one} test",
"tied with% {count} other% {test_one} test_plural": "à égalité avec% {count} others% {test_one} test"
```

When you need to synchronize translation files or download them using locize download, we get the following:

```
msgctxt "one} test"
msgid "tied with% {count} other% {test"
msgid_plural "tied with% {count} other% {test"
msgstr [0] "à égalité avec% {count} other% {test_one} test"
msgstr [1] "à égalité avec% {count} others% {test_one} test"

```
From this result questions follow.
In msgid and msgid_plural identical keys are stored. When requesting the key `tied with% {count} others% {test_one}` test we will not receive a translation.
And the second question.
Why is everything going after "_" placed in msgctxt?
As far as I know, msgctxt is used for Disambiguating Contexts.

**Comment by jamuhl** [comment]
Can you try again but with setting i18n format to "other" in your locize project settings? If using default format (i18next) it will handle part after `_` as context...I guess you're not using i18next as that format looks different -> so setting your project to other format should at least solve that issue.

**Comment by RomaKozeko** [comment]
I change project setting now it looks
![image](https://user-images.githubusercontent.com/44995086/62113459-4ce2b600-b2bd-11e9-8468-91a5f0279ebd.png)

But result not changed.
In locize:
```
"tied with %{count} other %{test_one} test": "à égalité avec %{count} other %{test_one} test",
"tied with %{count} other %{test_one} test_plural": "à égalité avec %{count} others %{test_one} test"
```

After download or sync:
```
msgctxt "one} test"
msgid "tied with% {count} other% {test"
msgid_plural "tied with% {count} other% {test"
msgstr [0] "à égalité avec% {count} other% {test_one} test"
msgstr [1] "à égalité avec% {count} others% {test_one} test"
```

**Comment by jamuhl** [comment]
Just had to confirm...detection of plural will automatically assume i18next format

We will need to see what we can do to avoid that handling...will ping you asap.

**Comment by jamuhl** [comment]
can you please try with locize-cli@4.8.3

**Comment by RomaKozeko** [comment]
I checked the new version of locize-cli. The problem with "msgctxt" is fixed.
But there was a problem with plural forms.
Initially we have:
```
msgid "tied with %{count} other %{test_one} test"
msgid_plural "tied with %{count} others %{test_one} test"
msgstr [0] "à égalité avec %{count} other %{test_one} test"
msgstr [1] "à égalité avec %{count} others %{test_one} test"
```

The values ​​in "msgid" and "msgid_plural" are different.
After downloading or synchronization, the plural keys are as follows:

```
msgid "tied with %{count} other %{test_one} test"
msgid_plural "tied with %{count} other %{test_one} test"
msgstr [0] "à égalité avec %{count} other %{test_one} test"
msgstr [1] "à égalité avec %{count} others %{test_one} test"
```

And when we try to get the plural translation by the key "tied with %{count} others %{test_one} test" we do not find it.

**Comment by jamuhl** [comment]
May I ask what framework you're using for i18n? As I understand pluralforms in gettext (PHP) it's like the accepted reply here: https://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext

```js
msgid "%d Comment"
msgid_plural "%d Comments"
msgstr[0] "%d Komentarz"
msgstr[1] "%d Komentarze"
msgstr[2] "%d Komentarzy"
```

**Comment by RomaKozeko** [comment]
We use https://github.com/grosser/gettext_i18n_rails
Yea this is pluralforms in gettext.
msgid and msgid_plural values are different. gettext stores two key values plural and singular "%d Comment" and "%d Comments".

**Comment by jamuhl** [comment]
while I understand it stores two keys (for translators) in the po file - I'm not sure that the plural key / msgid_plural is needed for the lookup for translations? Is that really the case...I was in the believe it uses the msgid to find a key and takes the right form based on the index in msgstr...?

**Comment by RomaKozeko** [comment]
I can’t say exactly how pluralforms in gettext work. But at the moment I can’t get the pluralform translation in this case:
` ns _ ('tied with %{count} other', 'tied with %{count} others', advocate_count) % {count: advocate_count}`
After finding translated strings with gettext_i18n_rails, we see different keys in msgid and msgid_plural. And after downloading from locize, the keys become the same. I would like them to stay different.

**Comment by jamuhl** [comment]
The current big problem is that for non singular/plural language we store the pluralforms in JSON format with suffixed key_0, key_1, ... reflecting the index used in gettext msgstr - so in those cases we do only have the msgid (=key) in singular. And there is no way to get that msgid_plural.

Can't you just call: `ns _ ('tied with %{count} other', 'tied with %{count} other', advocate_count) % {count: advocate_count}` in that case?

We will have to think of a solution for this one...but currently, I have no idea how to solve this - as we do not have the plural key/msgid_plural.

**Comment by jamuhl** [comment]
The only way I currently see is adding an option to combine msgid and msgid_plural into one json key instead of using msgid only...will need to create a PR in an upstream module...might take a few days to get that through...

**Comment by RomaKozeko** [comment]
Thank you!
I'll wait.

**Comment by jamuhl** [comment]
Could you please retry with: locize-cli@5.0.0

```
msgid "tied with% {count} other% {test_one} test"
msgid_plural "tied with% {count} others% {test_one} test"
msgstr [0] "à égalité avec% {count} other% {test_one} test"
msgstr [1] "à égalité avec% {count} others% {test_one} test"
```

results now in JSON

```
"tied with% {count} other% {test_one} test|#|tied with% {count} others% {test_one} test": "à égalité avec% {count} other% {test_one} test",
"tied with% {count} other% {test_one} test|#|tied with% {count} others% {test_one} test_plural": "à égalité avec% {count} others% {test_one} test"
```

So we can convert` po -> JSON (locize UI) -> po` keeping the msgid_plural by merging that into the JSON key.
