### ISSUE TITLE
Path mask for language as part of filename

### ISSUE THREAD

**Issue by chopkins123** [locize/locize-cli#32]
I'm trying to sync using a naming format like the below:
```    
locales
    ├── global
    │   ├── en-GB.translation.json
    │   ├── fr-FR.translation.json
```

I've tried using the arguments: 
--path-mask: `{{namespace}}/{{language}}.translation` 
--namespace: `global`
--language: `en-GB`

However I'm not seeing the keys copied into the locize portal, and the CLI is outputting the message `FINISHED` in green text colour. Have I made an error with the path-mask?

**Comment by adrai** [comment]
Hi @chopkins123 
Does it work without --path-mask?
What's your project-id?

**Comment by chopkins123** [comment]
Without the --path-mask I still get the same output on the first run. However if I run the same command a 2nd time I get the below output:

```
nothing to update for en/global
nothing to update for en-GB/global
syncing...
FINISHED
```

Looking in the `/locales` folder I can see 2 new folders `en` and `en-GB` have been created, both with the same empty `global.json` file inside.

I'm testing this against the demo project that locize creates, so `en` is set as the reference language, but I've created an `en-GB` language as well. This is the full command I'm using:

`locize sync -k MY_KEY -i MY_PROJECT -l "en-GB" -n "global" -p "C:\Git\ScratchPad\locize-sync-test\locales" -R false`

**Comment by adrai** [comment]
Can you send me the project-id?
If you want you can send an e-mail to support@locize.com

**Comment by adrai** [comment]
a few inputs:

you defined the namespace "global" that namespace is empty (or not published)

there's also nothing publish for the language "en-GB"

try this: `locize sync -k MY_KEY -i MY_PROJECT -p "C:\Git\ScratchPad\locize-sync-test\locales" -R false` (skip lng and namespace param)

or this: `locize sync -k MY_KEY -i MY_PROJECT -p "C:\Git\ScratchPad\locize-sync-test\locales" -R false -n "global" -s false`

or add some content to the en-GB/global namespace and publish it

I hope this helps

**Comment by chopkins123** [comment]
Created a new project with id `579cde95-2ad0-4e76-b6ae-0aa1a3df4427` and just the `en-GB` language with a single key `helloworld`.

Tried running the below commands and in both scenarios a new file is created at `\locales\en-GB\global.json` with the single `helloworld` key present.

- `locize sync -k MY_KEY -i MY_PROJECT -p "C:\Git\ScratchPad\locize-sync-test\locales" -R false`
- `locize sync -k MY_KEY -i MY_PROJECT -p "C:\Git\ScratchPad\locize-sync-test\locales" -R false -n "global" -s false`

If I run the command `locize sync -k MY_KEY  -i MY_PROJECT  -p "C:\Git\ScratchPad\locize-sync\locales" -R false -n "global" -s false -m
 "{{namespace}}/{{language}}.translation"` with my local translation file in the folder `locales\global\en-GB.translation.json`, the local file gets overwritten with the `helloworld` key

**Comment by chopkins123** [comment]
Found the issue:
Cloned the repo, can see in the `parseLocalLanguage` function uses `path.sep`. For the `path-mask` I'd used `{{namespace}}/{{language}}.translation` but as I'm on windows it should have been `{{namespace}}\{{language}}.translation`

All working now, keys were synced as expected, thanks for taking a look

**Comment by adrai** [comment]
no problem, welcome ;-)
