### ISSUE TITLE
Reference Language Not Found

### ISSUE THREAD

**Issue by JamesIves** [locize/locize-cli#33]
I'm running into an issue that is preventing me from syncing locize locally with my repository. I've got my reference language in my repo and within Locize set to `en` and I'm running `locize sync` in the `locales` directory and I end up with the error saying `Error: Reference language not found!`

My directory structure looks like the following:

<img width="290" alt="Screen Shot 2020-01-15 at 5 24 30 PM" src="https://user-images.githubusercontent.com/10888441/72477027-acc21000-37bc-11ea-8e89-31b62c8d31dc.png">

I feel like I'm missing something obvious here. Both of those file names are namespaces which exist in the Locize interface. 

Additionally is there any React documentation on disabling locize in production, and instead forcing i18n to use the synchronized json files in the locales directory instead of the API?

**Comment by adrai** [comment]
May I ask how your command line arguments look like?
Is the projectId correct?
You can also send us an email at: support@locize.com

**Comment by JamesIves** [comment]
I've been using the following:

`locize sync --api-key 123 --project-id 456 --format json`

`123` is my api key, and `456` is my project id in this case.

**Comment by JamesIves** [comment]
With `7.0.1`: `Error: Project not found!`

**Comment by adrai** [comment]
So yes, double-check the project-id.
If you like, you can send the project-id to support@locize.com so I can check.

**Comment by adrai** [comment]
Can you retry to run the command again?
