### ISSUE TITLE
Plural forms for a languages like ZH, KO, or JA

### ISSUE THREAD

**Issue by nilcolor** [locize/locize-cli#34]
Let say we have these strings we need to translate to a language without plural form. For Example Korean.
```
Wat|Got %{count} bonus -> %{count} 보너스를 받았습니다
Wat|Got %{count} bonuses -> %{count} 보너스를 받았습니다
```
When `locize download --format po` is called, we've got this for KO language

```
msgid ""
msgstr ""
"Project-Id-Version: locize\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language: ko\n"

msgid "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses"
msgstr "%{count} 보너스를 받았습니다"
```

Which obviously do not allow translation to be found.

```
λ locize --version
7.0.3
```

Is it possible to use `_plural` for strings like these anyway?
```
msgid "Wat|Got %{count} bonus"
msgid_plural "Wat|Got %{count} bonuses"
msgstr[0] "%{count} 보너스를 받았습니다"
msgstr[1] "%{count} 보너스를 받았습니다"
```
Not sure this is the correct but cannot find a better solution.

**Comment by adrai** [comment]
Are you using the i18next format?
If so, can you try how it looks like when you use `locize download --format po_i18next`?
To assist you further, it would be nice to know your projectId. (you can also send an email to support@locize.com)

**Comment by nilcolor** [comment]
> I don't know exactly what you want to achieve...

Maybe something like in the last example... `msgid "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses"` doesn't looks like a correct ID for a string. I'll check with `po_i18next` format.

**Comment by nilcolor** [comment]
> If so, can you try how it looks like when you use `locize download --format po_i18next`? Is there any difference?

`--format po_i18next` gives the same result.
Also, Locize UI show 2 rows (singular and plural forms) for all languages except JA, KO, ZH.

P.S. If possible, I'll share projectid later.

**Comment by adrai** [comment]
hmm... 
May I ask which i18n lib you are using?
If you like we can continue also via mail, because this seems not to be directly related to the cli.

**Comment by nilcolor** [comment]
This is kinda follow-up for this issue https://github.com/locize/locize-cli/issues/30
We are using https://github.com/grosser/fast_gettext to work with PO files.
They are downloaded from Locize via
```
locize download --project-id $LOCIZE_PROJECT_ID --ver latest --language ko --format po
```
Other languages like FR/IT/etc looks fine.
But those, with `"Plural-Forms: nplurals=1; plural=0\n"` are not working with plurals.

**Comment by adrai** [comment]
ok, can you try to save or rename the keys (in your reference language) in locize ui like this:
i.e. in your reference language:
```json
{
  "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses_plural": "Wat|Got %{count} bonuses",
  "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses": "Wat|Got %{count} bonus"
}
```
![image](https://user-images.githubusercontent.com/1086194/75678497-14a9b880-5c8e-11ea-91f1-1dbe3874bc15.png)

i.e. in zh
```json
{
  "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses_plural": "Wat | Got％{count}奖金",
  "Wat|Got %{count} bonus|#|Wat|Got %{count} bonuses": "Wat | Got％{count}奖金"
}
```
![image](https://user-images.githubusercontent.com/1086194/75678523-212e1100-5c8e-11ea-918b-df49cffa13a8.png)

_You need to have both keys._

after `locize download --format po` the po files should look like this:
```gettext
msgid ""
msgstr ""
"Project-Id-Version: locize\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"POT-Creation-Date: 2020-03-02T12:55:52.000Z\n"
"PO-Revision-Date: 2020-03-02T12:55:52.000Z\n"
"Language: en\n"

msgid "Wat|Got %{count} bonus"
msgid_plural "Wat|Got %{count} bonuses"
msgstr[0] "Wat|Got %{count} bonus"
msgstr[1] "Wat|Got %{count} bonuses"
```
and this in zh:
```gettext
msgid ""
msgstr ""
"Project-Id-Version: locize\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"POT-Creation-Date: 2020-03-02T12:56:13.000Z\n"
"PO-Revision-Date: 2020-03-02T12:56:13.000Z\n"
"Language: zh-cn\n"

msgid "Wat|Got %{count} bonus"
msgid_plural "Wat|Got %{count} bonuses"
msgstr[0] "Wat | Got％{count}奖金"
msgstr[1] "Wat | Got％{count}奖金"
```

**Comment by nilcolor** [comment]
So... "Add plural(s)" option from Locize is not working as expected? (8MB gif below, sorry)

![plurals_640](https://user-images.githubusercontent.com/163602/75757166-e76b1200-5d42-11ea-8ac0-5ba9274bc56e.gif)

@adrai your idea means to not use plurals but something special, correct? Also, this may (or will?) affect the way we sync data between Locize and local development. When plural keys collected locally, they synced exactly as shown on the attached gif.

**Comment by adrai** [comment]
If you use locize sync with po format the keys should be "generated" in locize automatically and your po files should look correct.
About the "Add plurals" button, this depends on your choosen i18n format. Seems you have selected "i18next", but you should choose "other".
Will ask the Frontend-Team about the exact behaviour of the "Add plurals" button.

_To summarize: I would suggest to:_

- change your i18n format to "other"
- use locize sync to syncronize your po files
