### ISSUE TITLE
Sync doest not work when using a filename that does not contain namespace. 

### ISSUE THREAD

**Issue by karelsoupaEMZ** [locize/locize-cli#35]
### Sync doest not work when using a filename that does not contain namespace. ### 
Sync works only locize => local files but local changes are not shown in locize.

* File structure:
Resources
├SharedResources.de.resx
├SharedResources.en.resx
├SharedResources.it.resx

* Command
locize s -i KEY-k ID --format resx --namespace ApiTranslations -m SharedResources.{{language}} 

Since there is a provided --path-mask parameter I would expect it to override the filename and work in a two way manner.

**Comment by adrai** [comment]
I don’t understand exactly what the issue is, but by default only changes in the reference language are detected.
If you don’t wish so, you need to use the parameter: --reference-language-only false

**Comment by karelsoupaEMZ** [comment]
--reference-language-only false was a typo in my issue description. The problem is that I have to name my files with translations the same as the namespace. Otherwise the sync does not work.

**Comment by adrai** [comment]
Can you share your —path-mask parameter?

**Comment by karelsoupaEMZ** [comment]
-m SharedResources.{{language}}

**Comment by adrai** [comment]
Yes, you need to include the {{namespace}} 
At least as folder like this: {{namespace}}/yourname.{{language}}

**Comment by adrai** [comment]
an alternative would be to rename your namespace in locize to SharedResources
this way you can use this mask: {{namespace}}.{{language}}

**Comment by karelsoupaEMZ** [comment]
I renamed SharedResources to something more suited for a namespace.
