### ISSUE TITLE
The cli tool strips out the xliff tags in Android

### ISSUE THREAD

**Issue by SalvatoreT** [locize/locize-cli#38]
The `locize-cli` tool doesn't honor the `xliff` tags in Android.

I copied the [translation example on the Android developer site](https://developer.android.com/guide/topics/resources/localization#mark-message-parts) (minus the `...`) and ran it through the format tool. Unfortunately, it stripped out all of the `xliff` tags.

```
$ locize format android-docs.xml --format android --dry true
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
  <!-- Example placeholder for a special unicode symbol -->
  <string name="star_rating">Check out our 5
    <xliff:g id="star">\u2605</xliff:g>
  </string>
  <!-- Example placeholder for a for a URL -->
  <string name="app_homeurl">
    Visit us at <xliff:g
    id="application_homepage">http://my/app/home.html</xliff:g>
  </string>
  <!-- Example placeholder for a name -->
  <string name="prod_name">
    Learn more at <xliff:g id="prod_gamegroup">Game Group</xliff:g>
  </string>
  <!-- Example placeholder for a literal -->
  <string name="promo_message">
    Please use the "<xliff:g id="promotion_code">ABCDEFG</xliff:g>" to get a discount.
  </string>
</resources>

<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="app_homeurl.value"> Visit us at http://my/app/home.html </string>
  <string name="prod_name.value"> Learn more at Game Group </string>
  <string name="promo_message.value"> Please use the ABCDEFG to get a discount.\n  </string>
  <string name="star_rating.value">Check out our 5 u2605 </string>
</resources>
reformatting /private/tmp/android-docs.xml...
would have reformatted /private/tmp/android-docs.xml...
FINISHED
```

Here's the example I used. [android-docs.xml](https://gist.githubusercontent.com/SalvatoreT/366cd3592c7e684c9bc607f85f2a8f21/raw/56c7b1a54687bcc7ca162d249e774c7fb9d98bf6/android-docs.xml)

**Comment by adrai** [comment]
Thanks for the info.
locize does only save the individual keys, not the original fil.
This is the reason all additional tags etc. are not there anymore.
Will investigate if there is something we can do for this.

**Comment by SalvatoreT** [comment]
I'm not super concerned about the XML comment tags, but I _do_ use the `<xliff:g>` placeholder tag to mark parts of the string so they're not translated.

Thanks for looking into this! I'm currently blocked by this, so if you have something in a beta I'd be happy to try it. I'm hitting a similar issue when I try to upload the string file to the site.

<img width="418" alt="Screen Shot 2020-04-28 at 11 57 53 PM" src="https://user-images.githubusercontent.com/1223008/80568570-1d77eb80-89ac-11ea-946c-b6c2175ee7f3.png">

**Comment by adrai** [comment]
There is perhaps a chance to handle this like this:

```xml
  <string name="star_rating">
    Check out our 5
    <xliff:g id="star">\u2605</xliff:g>
  </string>
```
```json
{
  "star_rating": "Check out our 5\n    <xliff:g id=\"star\">\\u2605</xliff:g>"
}
```

But it will just work if there is 1 `xliff:g` in the sentence

Would this be ok for you?

**Comment by adrai** [comment]
If you like, you can try v7.1.3

**Comment by SalvatoreT** [comment]
Thanks for taking a swing at it. Unfortunately, I still can upload my strings.

**Comment by adrai** [comment]
What is your output when using cli v7.1.3?

**Comment by SalvatoreT** [comment]
> If you like, you can try v7.1.3

Looks like we're making progress. This part of the resource isn't getting preserved: `<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">`.

Also, all the string keys are changing which will be a problem when trying to use the translated versions with different keys.

```diff
-  <resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
-  <!-- Example placeholder for a special unicode symbol -->
-  <string name="star_rating">Check out our 5
-    <xliff:g id="star">\u2605</xliff:g>

+ <?xml version="1.0" encoding="utf-8"?>
+ <resources>
+   <string name="app_homeurl.value">
+     Visit us at
+     <xliff:g id="application_homepage">http://my/app/home.html</xliff:g>

  </string>

-  <!-- Example placeholder for a for a URL -->
-  <string name="app_homeurl">
-    Visit us at <xliff:g
-    id="application_homepage">http://my/app/home.html</xliff:g>

+  <string name="prod_name.value">
+    Learn more at
+    <xliff:g id="prod_gamegroup">Game Group</xliff:g>

  </string>

-  <!-- Example placeholder for a name -->
-  <string name="prod_name">
-    Learn more at <xliff:g id="prod_gamegroup">Game Group</xliff:g>

+  <string name="promo_message.value">
+    <![CDATA[Please use the &quot;]]>
+    <xliff:g id="promotion_code">ABCDEFG</xliff:g>

  </string>

-  <!-- Example placeholder for a literal -->
-  <string name="promo_message">
-    Please use the "<xliff:g id="promotion_code">ABCDEFG</xliff:g>" to get a discount.

+  <string name="star_rating.value">
+    Check out our 5
+    <xliff:g id="star">\u2605</xliff:g>

  </string>

- </resources>

+ </resources>

reformatting /private/tmp/android-docs.xml...
would have reformatted /private/tmp/android-docs.xml...
FINISHED
```

**Comment by adrai** [comment]
next try with v7.1.4
key order can't be preserved

**Comment by SalvatoreT** [comment]
We're getting closer!

The resource tag was still clobbered a bit.
```
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
```
became
```
<?xml version="1.0" encoding="utf-8" xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2"?>
<resources>
```

Also, all the string keys gain a `.value` in their name.

**Comment by adrai** [comment]
xmlns:xliff is fixed now,
the .value was because of a bug in the format command

v7.1.5

**Comment by SalvatoreT** [comment]
This is much better!

The only nit I have is that the `<xliff:g>` tags are moved to the start of their own line. I'm not 100% if that will cause a problem or not.

```diff
-  <string name="app_homeurl">Visit us at <xliff:g id="application_homepage">http://my/app/home.html</xliff:g>

+  <string name="app_homeurl">Visit us at
+    <xliff:g id="application_homepage">http://my/app/home.html</xliff:g>
```

**Comment by adrai** [comment]
I think this will be ok... but I'm not an android expert ;-)

**Comment by SalvatoreT** [comment]
Thanks for fixing this issue!
