### ISSUE TITLE
Locize sync is not deleting keys

### ISSUE THREAD

**Issue by arturopie** [locize/locize-cli#39]
We are using the locize cli to upload keys for translation. We are using the PO format. 
We have found that `locize sync` is not deleting keys in locize that are not in our local PO files. 

This is the command we are using:

```bash
locize sync --api-key "${API_KEY}" --project-id "${PROJECT_ID}" --format po --namespace backend --path locales
```

We also try using `-S false`, and it does not work neither.

**Comment by adrai** [comment]
I'm not able to reproduce it.

Are you trying to delete a key in your reference-language or in another language?
If you want to delete a key in another language you may want to try: `--reference-language-only`
![image](https://user-images.githubusercontent.com/1086194/82479858-3bc89700-9ad3-11ea-8546-2a8c4d1e56ce.png)

**Comment by arturopie** [comment]
I want to delete the keys in all languages. I tried that option and it does not work neither

**Comment by adrai** [comment]
Can you share more information?
How does your cli output look like?

I'm really not able to reproduce it.

**Comment by arturopie** [comment]
We have 4 keys in Locize for the backend namespace. We removed one of those keys from our local PO file ($GETTEXT_LOCALES_PATH/en/backend.po). Then we run the following:

```
locize sync \
  --api-key "$LOCIZE_API_KEY" \
  --project-id "$LOCIZE_PROJECT_ID" \
  --format po --namespace backend \
  --path "$GETTEXT_LOCALES_PATH" \
  --reference-language-only false
```

This is the output we see:

```
adding 3 keys in en/backend...
syncing...
FINISHED
```

But in the Locize app, we still see 4 keys in all languages.

If download the translations from Locize:

```
locize download \
  --project-id "$LOCIZE_PROJECT_ID" \
  --ver latest \
  --namespace backend \
  --format po \
  --path "$GETTEXT_LOCALES_PATH"
```

I get 4 keys on my local PO file, but we were expecting 3

**Comment by adrai** [comment]
I have the same 4 keys in my setup, and I've done the same workflow. I can't reproduce it, so there  must be something different...

Some stuff I noticed:
You've currently 2 languages: **en** and **en-US**
You're always talking about language: **en** (which is your reference-language)

Currently your en-US/backend namespace has 4 keys, but your en/backend namespace is empty.
This looks strange... Shouldn't your reference language be filled with the keys?

Is it possible you're working on the wrong language?
![image](https://user-images.githubusercontent.com/1086194/82610561-eb2e6800-9bbe-11ea-9ca2-bccf502daefb.png)

**Comment by arturopie** [comment]
By empty do u mean there is no value for those 4 keys?
We will remove 'en' and uses en-US as reference language to see if it fixes the problem

**Comment by adrai** [comment]
Yes, let me know of this helps.

Btw. What’s the value of: $GETTEXT_LOCALES_PATH ?

I hope there is no language hardcoded in the path...

How does the directory look like after you execute the locize download command?

Are you using the latest version of the cli?

**Comment by abdullah90a** [comment]
Hey, sorry for the delay in getting back to you. We're picking GETTEXT_LOCALES_PATH from the app environment, no hardcoded language paths in the app.

We are using cli version 7.2.2

The 'gettext_locales' folder is part of the GETTEXT_LOCALES_PATH env variable. We've setup our download script to download po files to this folder. We have a script which goes through our app and removes keys not present in the app from the file -  - we then synchronize with the locize api with this same PO file.
<img width="573" alt="Screen Shot 2020-05-28 at 11 09 27 AM" src="https://user-images.githubusercontent.com/53870051/83159238-be54e600-a0d3-11ea-9803-a5307eda6a19.png">

**Comment by adrai** [comment]
Sorry, I can’t reproduce your issue...
I assume you have some troubles with the provided path....
maybe you need to set up the —path-mask option

also you “en_US” folder looks wrong to locize...
locize uses en-US...

So I think in your —path there is en_US but locize sync will download all languages... you have en and en-US in locize so it will pick randomly one or the other...


To reproduce this ob my side I need you to try the locize-cli sync command in a clean directory... to see if you can reproduce it there.

**Comment by abdullah90a** [comment]
Hey, we just figured out what was happening - it's as you said, locize sync needed the correct folder name.

We've updating the script we were using to sync to rename folders to the format Locize is expecting, and now we see keys being removed as intended.

Thank you very much for your support - I'd like to keep this ticket open for just a bit longer, will finish a round of testing and close by end of day today.
