### ISSUE TITLE
Support for HTML strings for Android

### ISSUE THREAD

**Issue by kpl-goel** [locize/locize-cli#4]
Currently some of our strings in Android project are formatted in HTML format. When we add translations in other languages in HTML format, then downloaded strings from locize escape characters `<` and `>` of HTML. Thus our strings.xml is not valid and builds fail.

For e.g., we have a string
```
<![CDATA[
            For <b>Sports</b>, try sport types, teams or leagues.<br />
            For <b>Movies</b>, try titles, actors or genres.<br />
            For <b>Shows</b>, try titles or genres.
]]>
```

Translated version is 
```
<![CDATA[
            Para <b>Deportes</b>, intente clase de deporte, equipos o ligas.<br />
            Para <b>Películas</b>, intenta títulos, actores, o géneros.<br />
            Para <b>Series</b>, intenta títulos o géneros.
]]>
```

when strings.xml for Android is downloaded, then locize downloads the following translation
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="error_no_search_results_subtitle">&lt;![CDATA[            
            Para &lt;b&gt;Deportes&lt;/b&gt;, intente clase de deporte, equipos o ligas.&lt;br /&gt;
            Para &lt;b&gt;Películas&lt;/b&gt;, intenta títulos, actores, o géneros.&lt;br /&gt;
            Para &lt;b&gt;Series&lt;/b&gt;, intenta títulos o géneros.
]]&gt;</string>
</resources>
```

And this is an invalid string

**Comment by adrai** [comment]
we are using this library: https://github.com/locize/android-string-resource
will look at it later today if we can do something

**Comment by adrai** [comment]
can you try with v3.9.6 ?
