### ISSUE TITLE
Sync removes existing translations for keys in Locize

### ISSUE THREAD

**Issue by michael-mao** [locize/locize-cli#41]
Our team is using i18next-scanner to extract keys from our codebase which we then upload to Locize using the sync command. However, this seems to overwrite any existing translations for existing keys on Locize. Is this the intended behaviour?

We are not using the `--update-values` flag, and looking at the README for the sync I don't see any mention that the values will be overwritten, only that keys will be added or removed.

**Comment by adrai** [comment]
Can you share a bit more information?
How does the directory structure look like?
Some sample files... before and after...
arguments used in sync command... cli output... etc...

**Comment by michael-mao** [comment]
Thanks for the response, I will try to list out the exact workflow we're using below.

We extract strings to JSON files in a `locales/` directory where the filename is the namespace we use in Locize, for example:

```
locales/
  en-US/
    test.json
  fr-FR/
    test.json
```

The JSON files would look something like below with keys mapped to empty string
```
{
  "Accepted": "",
  // more keys 
}
```

At this point we already have a translation on Locize for the "Accepted" key and just want to add new keys that have been tagged in the codebase.

We try to sync to Locize using the CLI

```bash
$ locize sync --api-key <api_key> --project-id <project_id> --format json --namespace test --path locales --reference-language-only false
```

output:
```bash
adding 59 keys in en-US/test...
removing 1 keys in fr-FR/test...
adding 58 keys in fr-FR/test...
syncing...
FINISHED
```

The result is that new keys are added but the translation we already had for the existing "Accepted" key on Locize is overwritten.

**Comment by adrai** [comment]
Ahh ok, I understand.
This is the expected behaviour. The sync command will synchronize locize with what you have locally. Your local directory is the master.

What you are looking for is something like a saveMissing feature via cli... right?
i.e. Just add new keys found via the i18next-scanner and not update and not delete anything, right?

**Comment by adrai** [comment]
For your use-case we just released a new cli version with a new command: `save-missing`
https://github.com/locize/locize-cli#push-missing-keys-to-locize-from-your-repository-or-any-other-local-directory

`locize save-missing --api-key <api_key> --project-id <project_id> --format json --namespace test --path locales --reference-language-only false`

**Comment by adrai** [comment]
I hope this is what you was looking for

**Comment by michael-mao** [comment]
That's great, thank you @adrai ! The save-missing functionality is what we're looking for

**Comment by adrai** [comment]
btw to preserve empty strings you may enable this option in your project’s settings: ![](https://user-images.githubusercontent.com/1086194/46956079-ae21fb80-d094-11e8-9137-2a1412679c85.png)
