### ISSUE TITLE
Package exports for '/project/node_modules/gettext-converter' do not define a valid './cjs/i18next2po' target

### ISSUE THREAD

**Issue by rishabh876** [locize/locize-cli#44]
After updating from version '7.0.3' to '7.6.3'. 
I have started getting this error when I try to sync.
npx locize sync -k xxx -i xxx

> Package exports for '/project/node_modules/gettext-converter' do not define a valid './cjs/i18next2po' target

More Info:
react: "^16.13.1",
react-native: "0.61.5"
npm : 6.13.1

**Comment by adrai** [comment]
Which node.js version are you using?

**Comment by rishabh876** [comment]
Its Node.js 13.0.1 @adrai

**Comment by adrai** [comment]
Ok, please use a more stable version of Node...
12 or 14
