### ISSUE TITLE
Sync does not update local changes when new key added locally and locize also has some key updated

### ISSUE THREAD

**Issue by rishabh876** [locize/locize-cli#45]
In case a new key is added locally and another key's value is updated on locize. In that case only new key is added to locize. But the key value change of some other does not get applied locally. So only upstream works and down stream doesn't. 
Are we only doing either upstream or downstream at a time? Both doesn't happen in one sync?

example:

Local file:
```
{
"oldKey":"oldValue",
"newKey":"Some Value" // new key
}
```

on Locize:
```
{
"oldKey":"newValue"
}
```

After Sync

Local file:
```
{
"oldKey":"oldValue", // Still old value here.
"newKey":"Some Value"
}
```

on Locize:
```
{
"oldKey":"newValue",
"newKey":"Some Value" // new key added 
}
```

The only workaround for this is to call sync twice.

**Comment by adrai** [comment]
Which cli arguments are you using?
Are you working in the reference language only?

**Comment by rishabh876** [comment]
Yes this is only for reference language. I haven't tested it on other languages. But I am able to reproduce this on reference language. 
No argument as such. 
`locize sync -k 9b077611-xxx-xxx-xxxxxxx -i 09c6491f-xxx-xxx-xxxxxxx`

**Comment by adrai** [comment]
Can you try with v7.6.4 ?

**Comment by rishabh876** [comment]
Working on this version. Thank you for the blazing fast fix. 👍
