### ISSUE TITLE
Flattened Translation Download containing nested keys

### ISSUE THREAD

**Issue by abdullah90a** [locize/locize-cli#47]
## 🐛 Bug Report

We've selected the 'flattened json' option as in our project setup - however, the cli downloads json files with nested keys. We have several keys with periods within them, and this is causing issues with our automated build scripts.

## To Reproduce

- Goto project settings.
- Under the 'Project Information' panel, select 'json flat' from the publish format menu.
- Download translation files through the locize cli.

## Expected behavior

Nested keys in the translated files should be flattened.

```js
"FirstPartOfTheString. SecondPartOfTheString." : "FirstPartOfTheTranslation. SecondPartOfTheTranslation."
```

should not become 

```js
"FirstPartOfTheString" : { 
    "SecondPartOfTheString": "FirstPartOfTheTranslation. SecondPartOfTheTranslation."
}
```

## Your Environment

- *runtime version*: i.e. node v10.15.0
- *Locize CLI*: >=7.5.0
- *os*: Mac, Linux

**Comment by adrai** [comment]
Try the --format flat argument

**Comment by abdullah90a** [comment]
@adrai - passing the flat flag to the cli did the trick. Thanks!
