### ISSUE TITLE
Download files bypassing TTL set on the project from locize

### ISSUE THREAD

**Issue by denissb** [locize/locize-cli#49]
## 🚀 Feature Proposal

It would be nice to have a way to use the `download` command with an argument to bypass the TTL caching on the CDN.

## Motivation
- Because we use `sync` we would like to be able to download the latest translations right after sync because by default it updates the keys but not the values, so values might be different between master and locize + developers might have new keys added that we also want to re-download.
- We have offline mode support in our app and for that reason we fetch translations during build time and use them as a fallback. The problem is that because we have caching configured on the project in Locize sometimes our translations are more stale than the time of build. 

## Example

Something like:
`locize download --ver production --bypass-cache=true`

**Comment by adrai** [comment]
Can you try with v7.6.13 there is no need to add an additional argument ;-)

**Comment by denissb** [comment]
@adrai Thanks for the help. v7.6.13 doesn't have the problem anymore.
