### ISSUE TITLE
Deletes .git when called without arguments

### ISSUE THREAD

**Issue by phihag** [locize/locize-cli#5]
When I run
```
node_modules/.bin/locize --project-id MY_PROJECT_ID --api-key MY_API_KEY s
```
(with the my project Id and API key) locize-cli deletes my .git and a lot of other directories!

The offending line seems to be https://github.com/locize/locize-cli/blob/591599144839729dd2b822f192dec00242ce24f9/sync.js#L494 .

locize-cli should not be calling `rimraf.sync` on random directories in the first place.

Likely, there should also be a check for correct arguments.

As an additional failsafe, locize-cli should check if one of the directories it is about to delete starts with a dot. If so, crash out immediately, because that can't be right, and can potentially destroy very important data.

**Comment by adrai** [comment]
Did you already try v3.12.1?

**Comment by phihag** [comment]
Yes, I am using version 3.12.1.

**Comment by adrai** [comment]
It still deletes the .git folder?

**Comment by adrai** [comment]
https://github.com/locize/locize-cli/commit/90baa1f44f6527c796de7ed73e235ea38cb1e48d#diff-39367c259f0252fc4bc764d86564411bR493

**Comment by phihag** [comment]
Oh, correction: With v3.12.1, `.git` remains. Thanks for the fix!
