### ISSUE TITLE
Add command to rename a key

### ISSUE THREAD

**Issue by Boscop** [locize/locize-cli#50]
## 🚀 Feature Proposal

Add command to rename a key

## Motivation

When a bunch of keys should be renamed, it's not equivalent to removing the keys and adding them under a new name because then the values of the non-reference languages are deleted.
It would be useful to have a subcommand for renaming keys.
It allows bulk changes much easier.

**Comment by adrai** [comment]
Such a feature is only possible if and when the api is extended with that functionality...
Alternatively, with the sync command you can do this, just adapt the files and sync.

**Comment by adrai** [comment]
btw: doing first an [add](https://github.com/locize/locize-cli#addingupdating-new-keys) in the reference language and then in the target languages and afterwards doing a [remove](https://github.com/locize/locize-cli#remove-keys) for all languages should already do what you are looking for.

**Comment by Boscop** [comment]
Shouldn't an `add` in the reference language automatically add the keys to all languages? 
(Just with no values for the non-reference languages.)
But so that the keys show up to translators in locize for non-reference languages.

**Comment by adrai** [comment]
No, it does the same as in the UI...
