### ISSUE TITLE
Add command to change a key's value

### ISSUE THREAD

**Issue by Boscop** [locize/locize-cli#51]
## 🚀 Feature Proposal

Add command to change a key's value for a given language.

## Motivation

It's much faster to run a CLI command than to login to locize's UI to change a key's value.
And it allows bulk changes much easier.

**Comment by adrai** [comment]
Should be already possible with the add command: https://github.com/locize/locize-cli#addingupdating-new-keys

**Comment by Boscop** [comment]
Ah, I didn't know that `add` also updates.
Because I looked at `locize add --help` which didn't show that it accepts `--update-values true`.
