### ISSUE TITLE
Command to sync only keys of reference language. (Not changing values.)

### ISSUE THREAD

**Issue by Boscop** [locize/locize-cli#52]
## 🚀 Feature Proposal

A subcommand to sync only keys of reference language. (Not changing values.)

## Motivation / Example

Consider the following workflow:
(Reference language is `en`. Path mask is `{{namespace}}.{{language}}`. Namespace is `translation`.)
Individual developers add keys to `translation.en.json` in their branches and do PRs against `master`.
Periodically, the `master` branch shall be synced with locize:
1. Keys added to `translation.en.json` should be uploaded with their values
2. Keys removed from `translation.en.json` should be removed from locize's server
3. **Existing keys' values should not be uploaded**: Keys in `translation.en.json` whose values differ from their values in locize should **NOT** have their values changed on either side. (This is because translators can edit the English values in locize, and those changes should not be overwritten.)
4. (Afterwards, `locize dl` is executed to download the latest values for all languages.)

Currently, step 2. cannot be done either with `sync` nor `save-missing`:
- Not with `sync` because:
> all non reference languages will always be just locally replaced by what is published on locize

(But non-reference languages' files should not be changed!)

- Not with `save-missing` because it doesn't remove deleted keys.

**Comment by adrai** [comment]
Sounds like a custom workflow.

I would consider do directly integrate the API.

**Comment by Boscop** [comment]
@adrai Custom in what way? Aren't all workflows custom? :)

Btw, if I only pass `--language en` to `locize sync`, will it still do this?
> all non reference languages will always be just locally replaced by what is published on locize

(It says `always`.)

**Comment by adrai** [comment]
it depends in which direction...
default sync is for reference language: local -> remote
other languages: remote -> local

and for other options there are this rules: https://github.com/locize/locize-cli#step-3-execute

--reference-language-only false
--compare-modification-time true
--update-values true
etc...

btw: with --dry true you can check what would happen without actually modifying anything
