### ISSUE TITLE
`locize remove` is too slow

### ISSUE THREAD

**Issue by Boscop** [locize/locize-cli#53]
## Bug Report

I needed to remove 652 keys from all (5) languages, and there is no bulk removal command (that would accept e.g. a file as arg, that lists all the keys to remove) so I ran a script that calls `locize remove translation <key>` for every key ("translation" is the namespace).
It was very slow for each key, in total the script took over 7 hours to run. Why is it so slow?
Ideally, removing one key should take only a few seconds maximum.

## To Reproduce

Have ~3k locize keys in 5 languages. Remove 652 with the CLI like described above.

## Expected behavior
Removing one key takes only a few seconds maximum.

## Your Environment
- *locize version*: locize CLI v7.6.14
- *os*: Linux

**Comment by adrai** [comment]
Probably you are calling the remove command serially?
Try to do something like this:

```sh
locize remove --language en namespace key1 &
locize remove --language en namespace key2 &
locize remove --language en namespace key3 &
```

> A single `&` symbol between commands will let each run independently without relying on the previous command having succeeded.

You can also try to use the `locize sync` command?

Alternatively, directly use the API: https://docs.locize.com/integration/api#update-remove-translations
set null value for the keys you want to delete.

**Comment by Boscop** [comment]
Right, I was calling them serially. (I tried using `&` after every of the 652 lines but it froze my computer for minutes and then 367 of those invocations failed with timeout error.)

I was considering `sync`, but wasn't sure if it fits my use case. But re-reading the doc, it could work.
Just to confirm:
If I pass `--reference-language-only false`, it won't change the values of any keys in locize, right?
And it won't download any keys that are only in locize, right?
So it will only push new keys & remove deleted keys from all languages, right?

**Comment by adrai** [comment]
`locize sync` will synchronize local(filesystem) and remote(locize), this means it will also download new (published) changes done in locize.
so `--reference-language-only false` will check not only for changes in your reference language but for changes in all languages

I don't unterstand why you should not want to download changes from remote to local....

As said, if you have a "special" workflow behaviour, use directly the API: https://docs.locize.com/integration/api#update-remove-translations

**Comment by Boscop** [comment]
Ah. So am I understanding it correctly that `locize sync --reference-language-only false` will not change the values of any key in locize but will set the value of each local key to the value it has in locize?

How does this "all non reference languages will always be just locally replaced by what is published on locize" change with `--reference-language-only false`?

**Comment by adrai** [comment]
I think we're talking past each other...
I suggest you create an empty folder somewhere on your local machine, then run `locize sync` once, and afterwards try to make some translation changes (locally and in locize) and execute `locize sync --dry true`  and `locize sync --reference-language-only false --dry true`
