### ISSUE TITLE
Download translation files

### ISSUE THREAD

**Issue by abdelfattah0atef** [locize/locize-cli#55]
I am trying to add a command in package JSON to just download my translations files (English and Arabic)

I used this
```
"download": "locize download"
```

and I created a new file in the root called `.locize` and I added my project id, API key, version and language but when running the above command it gives me an error

```
error: missing required argument `projectId`
```

**Comment by adrai** [comment]
the `.locize` can be in your working directory (`process.cwd()`) or in your home directory (`os.homedir()`): https://github.com/locize/locize-cli/blob/master/bin/locize#L11

Here you can check if it found something or not: https://github.com/locize/locize-cli/blob/master/bin/locize#L244
