### ISSUE TITLE
CVE on XLSX dependency

### ISSUE THREAD

**Issue by arturopie** [locize/locize-cli#56]
## 🐛 Bug Report

There is a known [security vulnerability on the XLSX](https://www.npmjs.com/advisories/1767) version that most recent locize-cli version (7.6.14) is using. I already see the most recent commit it's using a patched XLSX version, so the fix will probably be just to release a new locize-cli version.

## To Reproduce

Run 

```bash
yarn security
```

## Expected behavior

No vulnerabilities found

**Comment by adrai** [comment]
v7.6.15 has just been released
