### ISSUE TITLE
Sync creates `undefineden.json` instead of modify current `en.json`

### ISSUE THREAD

**Issue by Sebosek** [locize/locize-cli#57]
## 🐛 Bug Report

In our react app we're using a custom file structure with translations; more precise our file structure follows domain separation and/or colocations. Example of paths where we store translations.
```
G:\Projects\some project name\react-app\src\I18n\translations\common\en.json
G:\Projects\some project name\react-app\src\I18n\translations\errors\en.json
G:\Projects\some project name\react-app\src\Apps\InternalPortal\translations\en.json
G:\Projects\some project name\react-app\src\Apps\Onboarding\translations\en.json
G:\Projects\some project name\react-app\src\Apps\User\translations\en.json
G:\Projects\some project name\react-app\src\Widgets\BankAccounts\translations\en.json
G:\Projects\some project name\react-app\src\Widgets\Documents\translations\en.json
G:\Projects\some project name\react-app\src\Widgets\PersonBasicInfo\translations\en.json
...
```

So, we've decided to write a custom script that would utilise the sync command to sync app translations with Locise service. The script kinda works, the translations are uploaded to the Locise service properly, but the synced files have wrong names. The sync creates `undefineden.json` files instead of modifying the current `en.json` files.

## To Reproduce

A sample [codesandbox](https://codesandbox.io/s/react-i18next-forked-5mmln) to reproduce our file structure. Here is script which I'm talking about.

```js
#!/usr/bin/env node

const glob = require("glob-promise");
const path = require("path");
const chalk = require("chalk");
const locize = require("locize-cli");


const DRY_RUN = false;
const PATH_MASK = "{{language}}";

const version = process.env.LOCIZE_VERSION || 'latest';
const projectId = process.env.LOCIZE_PROJECTID || process.env.LOCIZE_PID;
const apiKey = process.env.LOCIZE_API_KEY || process.env.LOCIZE_KEY;

const { sep, resolve, join, parse } = path;
const root = resolve(__dirname, "..");
const start = new Date();

// TRANSLATIONS IN NAMESPACE
// G:/Projects/some project name/react-app/src/Apps/SampleNamespace/translations/cs.json
const translationsInNamespaceRegEx = new RegExp(`^.*\\${sep}([\\d\\w-_ ]*)\\${sep}translations\\${sep}.{2}\\.json$`);

// NAMESPACE IN TRANSLATIONS
// G:/Projects/some project name/react-app/src/I18n/translations/NamespaceCommon/cs.json
const namespaceInTranslationsRegEx = new RegExp(`^.*\\${sep}translations\\${sep}([\\d\\w-_ ]*)\\${sep}.{2}\\.json$`);

const round = (num) => +(Math.round(num + "e+2") + "e-2");
const isWidget = (file) => file.includes(`${sep}Widgets${sep}`);
const deriveNS = (file) => {
  let regexp;
  if (translationsInNamespaceRegEx.test(file)) {
    regexp = translationsInNamespaceRegEx;
  }

  if (namespaceInTranslationsRegEx.test(file)) {
    regexp = namespaceInTranslationsRegEx;
  }

  if (!regexp || typeof regexp.exec !== "function") {
    throw new Error(`Undefined RegExp for file ${file}!`);
  }

  const groups = regexp.exec(file);
  const namespace = groups[1];
  return isWidget(file) ? `widgets.${namespace}` : namespace;
};
const sync = (path, namespace, mask) => new Promise((resolve, reject) => {
  locize.sync({
    namespace,
    path: path,
    referenceLanguageOnly: false,
    pathMask: mask,
    apiKey,
    projectId,
    version,
    dry: DRY_RUN,
  }, (result) => {
    if (result === null) {
      console.log(`Sync ${namespace} ${chalk.greenBright("OK")}`);

      resolve();
    } else {
      console.log(`Sync ${namespace} ${chalk.bgRed("FAILED")}!`);

      reject(result);
    }
  });
});

const main = async (root) => {
  const files = await glob(`${root}/**/{translations,translations/**}/*.json`, { ignore: ['**/node_modules/**'] });
  const tasks = files
    .map(parse) // parse file path with path.parse to get file info
    .reduce((acc, curr) => acc.some(a => a.dir === curr.dir) ? acc : [ ...acc, curr ], []) // get only unique occurences
    .map(({ dir, base }) => {
      const file = join(dir, base); // create absolute path to file
      const namespace = deriveNS(file); // get namespace from file path

      console.log(`Running sync for '${namespace}'`);
      return sync(dir, namespace, PATH_MASK); // run locise-cli.sync
    });

  const results = await Promise.allSettled(tasks);
  if (results.every(({ status }) => status === "fulfilled")) return;

  throw new Error()
};

main(root)
  .then(() => console.log(chalk.greenBright("Succeeded")))
  .catch((err) => {
    console.log(chalk.red("Failed"));
    console.log(err);
  })
  .finally(() => {
    const now = new Date();
    const diff = now.getTime() - start.getTime();

    console.log(`\nDone in ${round(diff / 1000)}s`);
  });

```

## Expected behavior

The original language files are modified instead of create a new `undefineden.json` files.

## Your Environment

- *runtime version*: node v14.17.0
- *os*: Windows
- *locise-cli*: 7.6.15

**Comment by adrai** [comment]
Not yet checked in detail, but your mask does not seem to include any {{namespace}}:
`const PATH_MASK = "{{language}}";`
so this could lead to this strange undefined files 🤷‍♂️

**Comment by Sebosek** [comment]
Thanks for the reply, that's true, the mask doesn't contain a namespace, but the namespace is defined in the options parameter.
The thing with the mask is that it's not fully documented (at least I haven't found any) and it isn't clear what its purpose..?

Continue with a mask; how would the mask look like for structure `G:\Projects\some project name\react-app\src\Apps\User\translations\en.json` where User is a namespace and en.json language? Would it be `{{namespace}}/translations/{{language}}` and sync has to be run from within `G:\Projects\some project name\react-app\src\Apps\` folder?

**Comment by adrai** [comment]
try: `{{namespace}}/{{language}} `

**Comment by adrai** [comment]
btw: in the locize sync --help you should see this:

`This will define the folder and file structure; do not add a file extension (default: {{language}}/{{namespace}})`

**Comment by adrai** [comment]
> try: `{{namespace}}/{{language}} `

it may also be the `path: path` is undefined, the `dir` variable: `sync(dir, ...` 🤷‍♂️

**Comment by Sebosek** [comment]
Thanks for responses, unfortunately, none of above worked. In my case, the `options.languageFolderPrefix` was undefined and sync doesn't check the value (the check is in the bin/locize).
Quickfix is about adding `languageFolderPrefix: ""` to sync option and also PR for more long term solution is created.

**Comment by adrai** [comment]
Ahhh, this makes sense.... v7.6.16 was just released. It should work with that new version.
