### ISSUE TITLE
locize export with namespace inside file

### ISSUE THREAD

**Issue by razagill** [locize/locize-cli#6]
Hi,
Not sure where to ask this question so apologies if it's not the right place.
I'm using a webpack setup with locize and i18next to load my translation files instead of downloading them directly from locize in production. Currently if we export form locize the format of the exported file is something like this:
```
key: value
key: value
```
This is a little bit odd because if we then try to add them as a resource in i18next's `init` method, the format ought to be:
```
namespace:
  key: value
  key: value
```

I checked the API and that request also returns the former format, is there any way to have the namespace including inside the translation file?

**Comment by jamuhl** [comment]
Hi Raza, can you paste your code how you add the translation files into the resources option on init? You should be able to add the namespace there...

**Comment by jamuhl** [comment]
To reach us you can also use our email support@locize.com...or open an issue at one of the repos if you prefer...

**Comment by jamuhl** [comment]
i guess your using webpack context to get all files in locales folder and merge them to one object to be appended to resources.lng?!?

**Comment by razagill** [comment]
@jamuhl Thanks for the quick reply. Yes, to be specific I'm using this webpack loader https://github.com/alienfast/i18next-loader

**Comment by jamuhl** [comment]
but looks like that expects a structure like:

```
└── app
    └── src
    │  └── app.js
    └── locales
       ├── index.js
       ├── de
       │   ├── foo.json
       │   └── bar.yaml
       └── en
           ├── foo.json
           └── bar.yaml
```

so no need to have namespace in the file content...at least what i get from a fast look at that loader?!?

**Comment by razagill** [comment]
yes, that's exactly my structure as well but i18next does expect the namespace to be there inside the file. If you look at the examples in that loader, it also has the namespace inside the file e.g. https://github.com/alienfast/i18next-loader/blob/develop/test/data/basic-app-json/locales/en/main.json

**Comment by razagill** [comment]
What I would like to achieve is a workflow like this:

1. Download latest translation files from `locize`.
2. Put them in a specific folder.
3. Do the above steps during the build process.

I can potentially write a script for that, or better make a webpack plugin. But before going down that road I wanted to make sure is there a way to somehow add the namespace inside the exported files otherwise I would have to add that via the script/plugin as well.

Please let me know if the above approach sounds wrong to you as I'm not sure if something like this already exists for `locize`.

**Comment by jamuhl** [comment]
but looks like https://github.com/alienfast/i18next-loader/blob/develop/test/basename.spec.js#L25

key is main.test in ns main

**Comment by jamuhl** [comment]
no, there is currently no way to add the namespace on getting the file from locize - as that is not i18next default to have namespace in file...

**Comment by razagill** [comment]
Okay, seems like you are right. But then it must be a problem with my configuration? Do you see if there is anything wrong there? The only way I could make it work was to add the namespace inside the file otherwise the translations aren't loaded.

**Comment by jamuhl** [comment]
no...actually never used those loader myself...sorry...eventual you might add an issue there too - might be alienfast could be of help with this one

**Comment by razagill** [comment]
Thanks, I'll post a solution here if I find one.
