### ISSUE TITLE
I get this Error when I run copy-version command:

### ISSUE THREAD

**Issue by mhs-mlkn** [locize/locize-cli#60]
## 🐛 Bug Report

I get this error when i run copy-version command:

> copy failed from latest to production...
> Unauthorized: Api b1c*****-****-****-****-*********de2 not authorized for this scope (version) on project 15******-****-****-****-*********38e!

and I am 100% sure that my api-key and project-id are correct, I just copy them from my project setting page.

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

to copy latest version to production version

```js
// Paste the expected results here
```

**Comment by adrai** [comment]
Your mentioned API key is only allowed for the latest version, not for the production version.
You need to create a new key that is allowed for both versions:
![image](https://user-images.githubusercontent.com/1086194/140298568-03e4d40e-35cd-4b83-8155-27464d06edb0.png)

or has admin permission:
![image](https://user-images.githubusercontent.com/1086194/140298619-34eafb0f-c8a2-4f81-9e95-1d65df75e4e7.png)

**Comment by mhs-mlkn** [comment]
thanks for the response
