### ISSUE TITLE
Error running latest locize (v7.7.0) Linux binary

### ISSUE THREAD

**Issue by JaakkoA** [locize/locize-cli#61]
## 🐛 Bug Report

Installed locize with bash script (and also tried manually downloading binary for Linux). Same error in both cases.

## To Reproduce

Install locize and try to run it in Linux.

```js
$ curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh
$ locize 
cannot execute binary file: Exec format error
```

## Expected behavior

Locize should print out usage info when running without parameters, and older versions work without problems.

```js
$ locize
Usage: locize [options] [command]
```

## Your Environment

- *os*: Ubuntu 20.04.3 LTS

**Comment by adrai** [comment]
Does it work if you directly use node.js and install the cli via npm?

**Comment by adrai** [comment]
Can you try with v7.7.1 ?

**Comment by JaakkoA** [comment]
I was just trying with node.js and npm, and it installed newer version 7.7.1. This is now confirmed working with both npm and bash script. Thank you!
