### ISSUE TITLE
locize-cli installation fails on arm64

### ISSUE THREAD

**Issue by bensLine** [locize/locize-cli#62]
## 🐛 Bug Report
Installation of loicze-cli according to the [README](https://github.com/locize/locize-cli#with-shell-downloads-released-linux-or-macos-binaries) fails on Apple Silicon:
> Unsupported architecture arm64. Only x64 binaries are available.

The download executable for macOS from the latest release works on arm64 though: https://github.com/locize/locize-cli/releases/tag/v7.7.2

The instal [script](https://raw.githubusercontent.com/locize/locize-cli/master/install.sh) seems to be out of date for arm64
```bash
case $(uname -m) in
x86_64) arch="x86_64" ;;
*) arch="other" ;;
esac

if [ "$arch" = "other" ]; then
	echo "Unsupported architecture $(uname -m). Only x64 binaries are available."
	exit
fi
```

## To Reproduce
- Open the terminal on an arm64 Mac
- execute install script: `curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh`

## Expected behavior

the correct locize-cli executable for arm64 get's installed

## Your Environment

- *os*: Mac, Apple Silicon

**Comment by adrai** [comment]
The binary should work, but the install.sh script was not adapted: https://github.com/locize/locize-cli/commit/591588ccd62c091f821b16eeebf9e42c264ef734

This should work now.
