### ISSUE TITLE
Delete namespaces when using sync

### ISSUE THREAD

**Issue by VinceVachon** [locize/locize-cli#63]
I couldn't find this feature going through the doc and code.

## 🚀 Feature Proposal
If the file namespace1.json file is deleted from the local machine, delete it on the server when using `sync`.
This is working great for deleted keys when using `sync`.

## Motivation
This would avoid having to track delete files, login to locize app, open the namespace and remove it.

## Example
Delete an unused file (e.g `locale/en/namespace1.json`).
Use the `sync` command from the CLI.
The namespace get deleted from the server (locize app).

**Comment by VinceVachon** [comment]
Thanks for the quick answer! Would an option `sync api-key project-key --include-namespaces`  (default to false) would be conceivable?

**Comment by adrai** [comment]
probably more something like `--delete-remote-ns=true`... we'll check if this is doable...

**Comment by adrai** [comment]
v7.8.0 should do the trick ;-)

**Comment by VinceVachon** [comment]
Wow, that was quick. Thanks a lot.
