### ISSUE TITLE
locize sync: Existing keys not updating

### ISSUE THREAD

**Issue by agentsim** [locize/locize-cli#64]
## 🐛 Bug Report

Using the `sync` command, local changes to existing keys are not updated in locize.

## To Reproduce

1. `sync` a project.
2. Change a key in the primary language translation (ex: `strings-en.xml`)
3. `sync` a second time

## Expected behavior

The key that was changed locally should be updated in locize. Instead it is ignored and `sync` reverts the change.

## Your Environment

- locize cli version: 7.8.0
- MacOS

**Comment by adrai** [comment]
Yes, use: --update-values true

**Comment by adrai** [comment]
btw: make sure the version you're using is set to auto-publish mode

**Comment by agentsim** [comment]
My command-line is. I've validated that the env vars are correct.
`locize sync -k $API_KEY -i $PROJECT_ID --delete-remote-namespace true --update-values true -v latest -n $NAMESPACE -f android -m "strings-{{language}}" -p $TRANSLATION_PATH`

I added `--dry-run true`, the only output of the sync command was "FINISHED".
