### ISSUE TITLE
Sync command doesn't work when --version flag is specified

### ISSUE THREAD

**Issue by mhs-mlkn** [locize/locize-cli#66]
## 🐛 Bug Report

I want to sync my translation files with a version on remote otger than latest, but when I specify version using --version flag, command doesn't work at all, but if I just remove the --version flaf, it works fine.

## To Reproduce

```js
locize sync --path ./public/locales --update-values true --version release --api-key MY_API_KEY --project-id MY_PROJECT_ID
```

## Expected behavior

sync local files with specified version in command

## Your Environment

- *locize cli version*: 7.10.1
- *runtime version*: node v14
- *os*: Windows

**Comment by adrai** [comment]
--version is the argument for the CLI version, so this prints just v7.10.1

You need to use the correct argument for the locize version => `--ver` or `-v`
