### ISSUE TITLE
build cli for alpine

### ISSUE THREAD

**Issue by chrillep** [locize/locize-cli#67]
## 🚀 Feature Proposal

add target for alpine 
https://github.com/vercel/pkg#targets
check os via 
```sh
cat /etc/os-release
```
https://serverfault.com/questions/805389/which-os-is-running-in-my-docker-container
## Motivation

ability to run locize on alpine in minimal docker container
sidenote: add compression? not sure about the caveats.
https://github.com/vercel/pkg#compression
## Example

Please provide an example for how this feature would be used.

**Comment by adrai** [comment]
v7.11.0 should work also for alpine...
https://github.com/locize/locize-cli/releases
would be nice if you could test `curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh`

**Comment by chrillep** [comment]
on it :)

**Comment by chrillep** [comment]
```sh
/app $ curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh
sh: syntax error: unexpected "else"
```

**Comment by chrillep** [comment]
the binary aswell! 🚀
