### ISSUE TITLE
Locize cli doesn't read `.env` file

### ISSUE THREAD

**Issue by Carduelis** [locize/locize-cli#69]
### Problem

I've added variables of project id and API key to `<root>/.env` file and use `locize sync` in my `package.json` command.
It doesn't respect added variables with the correct spelling (I've checked [the source code](https://github.com/locize/locize-cli/blob/c1676d1bcfda9a65172d663ee9b7d40fc3033812/bin/locize#L58-L63) as well)

`<root>/.locize` works, but I need `.env` file, cause I need to store variables Secretly.

I've tried [the guide](https://www.genui.com/resources/env-variables-json)  and it works with `echo`, but doesn't work with locize.

```
"echo-test": "dotenv cross-var echo $LOCIZE_API_KEY" // prints the value (expected)
"pure-test": "dotenv cross-var $LOCIZE_API_KEY" // prints the value as a missing command (expected)
"locize:sync": "dotenv cross-var locize sync --api-key $LOCIZE_API_KEY" // doesn't work
````

### Environment

Windows 10, Node 16.14.2

**Comment by adrai** [comment]
For me `"locize:sync": "dotenv cross-var locize sync"` is working...
just make sure you do not have a .locize config file
