### ISSUE TITLE
Locize sync alters my `.json` files

### ISSUE THREAD

**Issue by Carduelis** [locize/locize-cli#70]
### Problem

No matter which setting I set to "Publish Format"
![image](https://user-images.githubusercontent.com/3492820/174784479-77c80ff5-0a13-4f91-90a5-f9bf2dd5295e.png)

After running `locize sync` command it converts:
```
{
   "1.4-billion": "Over 1.4 billion"
}
```

to a nested structure:
```
{
   "1": {
       "4-billion": "Over 1.4 billion"
    }
}
```

Which is not desirable behavior.

**Comment by adrai** [comment]
did you try with the flat format argument? `--format flat`
