### ISSUE TITLE
Ambiguous --compare-modification-time flag behavior

### ISSUE THREAD

**Issue by ravecat** [locize/locize-cli#71]
## 🐛 Bug Report

Faced with strange behavior for sync command wth `--compare-modification-time` flag. Сommand with flag considers the remote service as a master and I haven't ability to remove a key. 

Current behavior available for requirements:

- sync includes non-reference language
- autopublish setting is enabled 
- empty string handling is off

### `--compare-modification-time` is enabled

Command: `locize sync --reference-language-only false --compare-modification-time true --format flat`

| case                                                                                                                       | initial local state | initial service state | expected behavior                                    | expected local state | expected service state | actual local state                               | actual service state | actual behavior  |
| -------------------------------------------------------------------------------------------------------------------------- | ------------------- | --------------------- | ---------------------------------------------------- | -------------------- | ---------------------- | ------------------------------------------------ | -------------------- | ---------------- |
| Developer add a new keys and parser creates a new key-value pair (for non-reference language value is empty (`""`) string) | `{"foo": ""}`       | `{}`                  | sync should add a new key to service                 | `{"foo": ""}`        | `{"foo": ""}`          | ✅                                               | ✅                   | ✅               |
| Developer excludes old keys and parser removes a key-value pair from artifact)                                             | `{}`                | `{"foo": "foo"}`      | sync should remove key from service                  | `{}`                 | `{}`                   | ❌ sync update local key value with remote value | `{"foo": "foo"}`     | `{"foo": "foo"}` |
| Developer updates a key value                                                                                              | `{"foo": "newfoo"}` | `{"foo": "foo"}`      | sync should update local key value with remote value | `{"foo": "foo"}`     | `{"foo": "foo"}`       | ✅                                               | ✅                   | ✅               |
| Translator updates a key value                                                                                             | `{"foo": "foo"}`    | `{"foo": "newfoo"}`   | sync should update local key value with remote value | `{"foo": "newfoo"}`  | `{"foo": "newfoo"}`    | ✅                                               | ✅                   | ✅               |
| Translator remove a key value                                                                                              | `{"foo": "foo"}`    | `{"foo": ""}`         | sync should update local key value with remote value | `{"foo": ""}`        | `{"foo": ""}`          | ✅                                               | ✅                   | ✅               |

Artifacts and service stores out-of-date keys, because we haven't abiltity to remove keys automatically inside a CI process

For comparison, I will give the results of the command with disabled flag

### `--compare-modification-time` is disabled

Command: `locize sync --reference-language-only false --format flat`

| case                                                                                                                       | initial local state | initial service state | expected behavior                                    | expected local state | expected service state | actual local state | actual service state | actual behavior  |
| -------------------------------------------------------------------------------------------------------------------------- | ------------------- | --------------------- | ---------------------------------------------------- | -------------------- | ---------------------- | ------------------ | -------------------- | ---------------- |
| Developer add a new keys and parser creates a new key-value pair (for non-reference language value is empty (`""`) string) | `{"foo": ""}`       | `{}`                  | sync should add a new key to service                 | `{"foo": ""}`        | `{"foo": ""}`          | ✅                 | ✅                   | ✅               |
| Developer excludes old keys and parser removes a key-value pair from artifact)                                             | `{}`                | `{"foo": "foo"}`      | sync should remove key from service                  | `{}`                 | `{}`                   | ✅                 | ✅                   | ✅               |
| Developer updates a key value                                                                                              | `{"foo": "newfoo"}` | `{"foo": "foo"}`      | sync should update local key value with remote value | `{"foo": "foo"}`     | `{"foo": "foo"}`       | ✅                 | ✅                   | ✅               |
| Translator updates a key value                                                                                             | `{"foo": "foo"}`    | `{"foo": "newfoo"}`   | sync should update local key value with remote value | `{"foo": "newfoo"}`  | `{"foo": "newfoo"}`    | ✅                 | ✅                   | ✅               |
| Translator remove a key value                                                                                              | `{"foo": "foo"}`    | `{"foo": ""}` equals `{}`         | sync should update local key value with empty value  | `{}`        | `{}`          | ❌                 | `{"foo": "foo"}`     | `{"foo": "foo"}` |

The lack of this command is saving the translation if the translator wants to remove it. As seen, the problems start when the user wants to delete the key value in locize. However locize does not store empty strings and removes the key

## Questions

1. Could you clarify compare logic for `--compare-modification-time` flag? 

2. Which logic to choose for share control between the service and the development process (locize should only manage the values of keys, creation/deletion should be done by developers)?

## Expected behavior

The flag must take into account the latest changes between service and local folder

## Your Environment

- *runtime version*: node v16.8.0
- *module version*: 7.6.17
- *os*: MacOS
- *any other relevant information*

**Comment by adrai** [comment]
Just tried to reproduce your second case:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1086194/175820068-8856633c-74b7-45ae-b0d5-5e81048d6a3e.png">
this seems to work for me.

---

The last case without `--compare-modification-time` behaves as intended, because "your local repository is the master": 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1086194/175820256-617e8818-99a8-447a-bce9-4937c94c394b.png">

---

In general the CLI will always compare with what is published. To see what is actually published, check your namespace: https://docs.locize.com/integration/api#fetch-namespace-resources

---

The logic of `--compare-modification-time` is simple: it just compares the [last-modified header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) of the published translations with the [mtime](https://nodejs.org/api/fs.html#class-fsstats) of the local file. The newer datetime is the master namespace.

---

So when should `--compare-modification-time` be used and when not?

-> Usually, the developers will only work locally, and only with the reference language. So, adding new keys or removing old keys would automatically be synchronized with locize, but existing value updates in locize would be synched back locally.
Often this is the default process. => in this case `--compare-modification-time` is not necessary.

But it may be there is a mix in the process, so sometimes new keys gets added to locize directly sometimes only locally, etc... In this situation `--compare-modification-time true` is favorable.

**Comment by ravecat** [comment]
@adrai thank you for answer, could you take advice how to find modification time for locize translation. every sync values from locize rewrite of local translation values, it looks like remote changes always take precedence

**Comment by adrai** [comment]
Sorry, I don't understand your question. Can you please elaborate?

**Comment by ravecat** [comment]
@adrai you mentioned

> it just compares the [last-modified header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) of the published translations with the [mtime](https://nodejs.org/api/fs.html#class-fsstats) of the local file. The newer datetime is the master namespace.

I have abilty to get mtime 

<img width="965" alt="Screen Shot 2022-07-08 at 11 46 14" src="https://user-images.githubusercontent.com/24782863/177965840-c7431648-5b16-4144-b3e7-5264c52a9742.png">

So, have any ability to get modiified time for locize translation version? Because every sync remote translation rewrite local changes and I want to compare mtime and modification time from header

**Comment by adrai** [comment]
Like said, the [last-modified header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) of your published translations (https://docs.locize.com/integration/api#fetch-namespace-resources)

i.e. for the https://locize.com website the downloaded translations are: https://api.locize.app/3d0aa5aa-4660-4154-b6d9-907dbef10bb2/production/en/landingpage
In the response header you'll find it:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1086194/177966959-411b70e0-fc8e-4a62-b778-6fe8fe3a42f7.png">
