### ISSUE TITLE
version contains strange undeletable namespaces

### ISSUE THREAD

**Issue by ravecat** [locize/locize-cli#72]
## 🐛 Bug Report

Faced with the strange namespace list in API response ([fetch namespace list API](https://docs.locize.com/integration/api#fetch-namespace-resources)), which hidden from locize.app and unavailable for deletion

Web version contains current namespace list

<img width="487" alt="Screen Shot 2022-07-12 at 00 55 32" src="https://user-images.githubusercontent.com/24782863/178372476-7910c9e1-534e-40a6-a9ed-71b9cc801f09.png">

But API response contains strange versions

<img width="487" alt="Screen Shot 2022-07-12 at 00 54 43" src="https://user-images.githubusercontent.com/24782863/178372579-07860ec8-ecf4-4f56-b878-bf64ae90c5ee.png">

Versions available for fetch keys, but unavailable for deletion 

```bash
{
    "name": "ValidationError",
    "message": "Bad Request: Namespace does not exist!",
    "more": [
        "namespace"
    ]
}
```

I started investigating this issue when I encountered strange behavior when [downloading](https://github.com/locize/locize-cli#download-current-published-files) current published translations

<img width="1792" alt="Screen Shot 2022-07-12 at 01 02 18" src="https://user-images.githubusercontent.com/24782863/178373180-7d85c2f3-ea90-4a8e-8e2a-adb5334a0382.png">

```bash
ENAMETOOLONG: name too long, open 'locales/en/England.%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520Premier%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520League%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520(Simulated%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520Reality%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520League)%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525202x45%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520mins.https.json'
```

Auto-publish is disabled for version

Could you clarify this behavior?

## Expected behavior

Web-version and response contain equals namespace list

## Your Environment

- *runtime version*: node v16.8.0
- *module version*: 7.6.17
- *os*: MacOS

**Comment by adrai** [comment]
I suspect these are old wrong namespaces that were not correctly deleted or renamed last year.
It should be cleaned now. If this happens again, please send an email to support@locize.com
