### ISSUE TITLE
Mapping between CLI params and config options

### ISSUE THREAD

**Issue by ravecat** [locize/locize-cli#73]
Should add information to docs about mapping between CLI options and config .locize options (mentioned [here](https://github.com/locize/locize-cli#other-information))

Part of CLI params don't availble from `.locize` config (in particular `format`, `compare-modification-time`, etc)

**Comment by adrai** [comment]
Yes, this is intended.
Only the parameters listed here are mapped: https://github.com/locize/locize-cli#other-information
