### ISSUE TITLE
Locize sync results in FetchError

### ISSUE THREAD

**Issue by datainvestor** [locize/locize-cli#74]
When running locize sync with provided api-key and porject-id:
`locize sync --api-key *** --project-id ***` in the locales folder in command line

I am getting the following error:

`FetchError: request to https://api.locize.app/languages/**** failed, reason: unable to get local issuer certificate`

Any idea how to fix this?

Using Visual Studio Code and Windows 10.

**Comment by adrai** [comment]
Sorry, not able to reproduce it.
Do you have some local proxy, VPN, firewall etc. that influences your network?

**Comment by datainvestor** [comment]
Hmm, I do have ZScaler on, maybe it is blocking Locize CLI.

**Comment by jamuhl** [comment]
@datainvestor were you able to solve this issue by testing disabling ZScaler?
