### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by Odinwan** [locize/locize-cli#75]
When running locize sync with provided api-key and porject-id:
locize sync --api-key ${apiKey} --project-id ${projectId} --path public/locales/ --language en --update-values true
or 
locize sync --api-key ${apiKey} --project-id ${projectId} --path public/locales/

I am getting the following error:

![image](https://user-images.githubusercontent.com/47388945/189306026-aca83a14-c7bb-4972-aa0d-889ed7235a8f.png)

Any idea how to fix this?

Using WebStrorm and mac OS.

**Comment by adrai** [comment]
Can you try with v7.12.7?
