### ISSUE TITLE
install.ps1 automatic figuring out of download url version has broken

### ISSUE THREAD

**Issue by shinpou** [locize/locize-cli#76]
## 🐛 Bug Report

Install.ps1 can no longer figure out latest version number

![Screenshot 2022-09-13 at 10 47 54](https://user-images.githubusercontent.com/2289820/189842374-428da3c6-bef7-48d7-aeb4-649f2933bf1c.png)

Breaks on this part:
```powershell
    $Response.Links |
      Where-Object { $_.href -like "/locize/locize-cli/releases/download/*/locize-${OS}" } |
      ForEach-Object { 'https://github.com' + $_.href } |
      Select-Object -First 1
```

This part returns a null, so same cause as #77 

## To Reproduce

Called install.ps1 on mac and azure devops, and both started failing this morning

## Expected behavior

install.ps1 has been able to figure out the latest version until now

## Your Environmen

- osx, azure devops agent running ubuntu

**Comment by adrai** [comment]
Should work now...

**Comment by shinpou** [comment]
Confirmed to work on azure devops and mac
