### ISSUE TITLE
bug(install): binary install not working

### ISSUE THREAD

**Issue by chrillep** [locize/locize-cli#77]
for some reason the shell script  isn't working.
```sh
curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh
```
debugged it to these lines . 
something is wrong at github perhaps :/ 

https://github.com/locize/locize-cli/blob/8bb00613fc3249c8e95f905c8181accf7ffda259/install.sh#L29-L34

maybe log / output something if finding releases fail instead of just exit? :)
```sh
if [ ! "$locize_asset_path" ]; then
    echo "failed to find a release"
    exit 1;
fi
```

works on.

- [x] macos
- [ ] linux
- [x] alpine-linux
- [ ] windows https://github.com/locize/locize-cli/issues/76

ref:

[One Liner to Download the Latest Release from Github Repo.md](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8)

**Comment by chrillep** [comment]
relates to #76 76

**Comment by chrillep** [comment]
yeah i was depending on this script so maybe ill just lock to a release version instead :)

**Comment by shinpou** [comment]
Is there any possibility of maybe using https://github.com/locize/locize-cli/releases/latest always if the version parameter is not provided? I guess using the github api is out of the question considering it requires authentication...

**Comment by adrai** [comment]
just fixed the install.sh script

**Comment by chrillep** [comment]
curl -s https://api.github.com/repos/locize/locize-cli/releases/latest

**Comment by chrillep** [comment]
> Is there any possibility of maybe using https://github.com/locize/locize-cli/releases/latest always if the version parameter is not provided? I guess using the github api is out of the question considering it requires authentication...

curl -s https://api.github.com/repos/locize/locize-cli/releases/latest seems to work

**Comment by chrillep** [comment]
> just fixed the install.sh script

ill try it thanks

**Comment by chrillep** [comment]
ty works on. 

- [ ] macos
- [ ] alpine

**Comment by shinpou** [comment]
install.ps1 still fails for me, appears to break on this part:

```
    $Response.Links |
      Where-Object { $_.href -like "/locize/locize-cli/releases/download/*/locize-${OS}" } |
      ForEach-Object { 'https://github.com' + $_.href } |
      Select-Object -First 1
```

This part returns a null, so same cause as this issue

**Comment by adrai** [comment]
just fixed sh... currently checking ps1 ;-)

**Comment by chrillep** [comment]
@adrai sry but running into this again
but now i get the error message! =)

```sh
curl -fsSL https://raw.githubusercontent.com/locize/locize-cli/master/install.sh | sh
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
failed to find a release on github
```

**Comment by adrai** [comment]
OMG, they just changed it again....

**Comment by chrillep** [comment]
> OMG, they just changed it again....

yeah i hear u :/

**Comment by adrai** [comment]
ok, now it should work

**Comment by chrillep** [comment]
> ok, now it should work

yep ty. hopefully they don't change this again anytime soon
