### ISSUE TITLE
The sync command crashes with Error: Callback was already called

### ISSUE THREAD

**Issue by selindho** [locize/locize-cli#79]
## 🐛 Bug Report

`locize sync` crashes with `Error: Callback was already called.` when using the `android` format and there are multiple `<plurals>...</plurals>` blocks.

## To Reproduce
Given a directory with the following structure:
```
.
`-- en
    `-- strings.xml
```

where `strings.xml` contains the following:
```xml
<?xml version="1.0" encoding="utf-8"?><resources>
    <plurals name="a">
        <item quantity="one">A</item>
        <item quantity="other">AA</item>
    </plurals>
    <plurals name="b">
        <item quantity="one">B</item>
        <item quantity="other">BB</item>
    </plurals>
</resources>
```
Run the following:

`locize sync --project-id {omitted} --api-key {omitted} --format android --dry=true`

This results in:
```
/Users/user/.nvm/versions/node/v18.12.1/lib/node_modules/locize-cli/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/user/.nvm/versions/node/v18.12.1/lib/node_modules/locize-cli/node_modules/async/dist/async.js:324:36
    at /Users/user/.nvm/versions/node/v18.12.1/lib/node_modules/locize-cli/node_modules/async/dist/async.js:248:17
    at /Users/user/.nvm/versions/node/v18.12.1/lib/node_modules/locize-cli/parseLocalLanguage.js:151:11
    at FSReqCallback.oncomplete (node:fs:208:5)

```
## Expected behavior

If the contents of `strings.xml` are replaced with:

```xml
<?xml version="1.0" encoding="utf-8"?><resources>
    <plurals name="a">
        <item quantity="one">A</item>
        <item quantity="other">AA</item>
    </plurals>
</resources>
```
The output of `locize sync --project-id {omitted} --api-key {omitted} --format android --dry=true` is:
```
adding 2 keys in en/strings...
would add a.one, a.other in en/strings...
syncing...
FINISHED

```
I expect the sync work in the same manner, even if there are multiple `plurals`-blocks in `strings.xml`.

## Your Environment

- *runtime version*: node v18.12.1
- *module version*: 7.12.8
- *os*: Mac

**Comment by adrai** [comment]
v7.12.9 should fix this
