### ISSUE TITLE
global import

### ISSUE THREAD

**Issue by rfussien** [locize/locize-cli#8]
me again,

On the locize web interface, it is possible to download a json nested file wich contains all the language and all the name space.

It'd be very cool to be able to do the same with the cli.

First I thought I'd use sync, but it seems it's for a one way sync (local -> locize) and not the other way around.

Then I thought I could do that with the download command, but it seems that if I don't specify a language, it takes the reference language only. So would it be possible to have a --all option to the download command to get the same result as the web interface ? Or have I miss something ?

Thanks

**Comment by adrai** [comment]
The sync command is two way. It will always download everything (published) from locize.
And the download command should work too.
Make sure you have published the translations. The cli will only download the published translations.

**Comment by rfussien** [comment]
So when I say sync is one way, that's what I mean:

With an empty directory `locales`:

```bash
locize sync --path locales
```

I have the locale tree I was expected with all the languages and namespace.
Now, I work on my app, which use the locize backend. It adds keys and value to locize and when I use sync again, it deletes all the work that has been done on locize. I would have expected to retrieve that work.

With `download`, it gets one language at the time (_if I ain't misunderstanding_).

**Comment by adrai** [comment]
With the download command you can download a whole version => `locize download`
Just make sure everything is published and skip language and namespace argument on the cli.
If you prefer you can send us an email at support@locize.com with the project-id id I will send you a complete cli call example.

**Comment by rfussien** [comment]
My bad, the language came from the config file

**Comment by adrai** [comment]
ok.
Should be something like this: `locize download --format json --clean true --project-id my-project-id --ver latest --path locales`

**Comment by rfussien** [comment]
works like a charm now. Thanks for your time
