### ISSUE TITLE
The download command fails with an error when using the android format

### ISSUE THREAD

**Issue by selindho** [locize/locize-cli#80]
## 🐛 Bug Report

The download command fails with an error when using the android format.

## To Reproduce

Run the following:

`locize download --project-id {omitted} --api-key {omitted}  --format android`

This results in the following error:

```
Invalid content for "android" format!
Cannot read properties of undefined (reading 'type')
```

The primary namespace I'm using contains some 900 translation keys, so haven't figured out which key that causes this yet. Tried testing some different cases in an otherwise empty namespace, but they have all worked so far. 

## Expected behavior

When omitting the `--format android` flag, the download succeeds, resulting in the following directory structure:

```
.
|-- en
|   `-- strings.json
|-- et
|   `-- strings.json
|-- fi
|   `-- strings.json
|-- lt
|   `-- strings.json
|-- lv
|   `-- strings.json
|-- ru
|   `-- strings.json
`-- sv
    `-- strings.json
```

I expect the download to work in the same way when using the `--format android` option, but resulting in Android string resources files instead of JSON.

## Your Environment

- *runtime version*: node v18.12.1
- *module version*: 7.12.9
- *os*: Mac

**Comment by adrai** [comment]
Can you please send an email to support@locize.com with the project-id so we can check?
I suspect the translation content is not compatible to the android format.

**Comment by selindho** [comment]
> Can you please send an email to [support@locize.com](mailto:support@locize.com) with the project-id so we can check?
> I suspect the translation content is not compatible to the android format.

Will do.

**Comment by selindho** [comment]
Another noteworthy thing which I forgot to mention: all translations were created using the `sync` command with the `--format android` option.

**Comment by adrai** [comment]
v7.12.10 should fallback without crashing, when there are missing string-array elements
