### ISSUE TITLE
vulnerabilities on npm install

### ISSUE THREAD

**Issue by jacklrs** [locize/locize-cli#81]
## 🐛 Bug Report

There are 6 high severity vulnerabilities reported on npm install this package

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```
mkdir test 
cd test
npm init -y
npm i -D locize-cli
```

## Expected behavior

No vulnaribilities, at least npm audit fix should work.

## Your Environment

- *runtime version*: node 18.12.1; npm 8.19.2
- *module version*: 7.13.1
- *os*: Mac

**Comment by adrai** [comment]
There's not much we can do here...
The "issues" are triggered by nth-check in rdotjson...

Waiting for this to land: https://github.com/kawanet/rdotjson/pull/11

**Comment by adrai** [comment]
v7.13.2 should address this
