### ISSUE TITLE
`locize format` removes comments from `fluent files`

### ISSUE THREAD

**Issue by girisagar46** [locize/locize-cli#82]
## 🐛 Bug Report

Comments are supported in fluent files. REF: https://projectfluent.org/fluent/guide/comments.html, but whrn I run `locize format`, it removes all the comments. 

## To Reproduce

Let's assume we're working with a fluent file called `home.ftl`
```fluent
# The login page
login-username = Your username

login-password = Your password
```

When I run following command:
```bash
locize format home.ftl --format fluent
```

The output I get is:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/6840782/216814524-62e7fbfd-ba3c-45fe-a2fa-b9b9f9e0ee44.png">

And the fluent file `home.ftl` is modified to:
```fluent
login-password = Your password

login-username = Your username
```

## Expected behavior

Preserve comments in fluent files.

## Your Environment

- *locize-cli* version: `7.13.2`
- *os*: Mac

**Comment by adrai** [comment]
The format command is trying to respect the handling that also the download or sync command would do.
And since locize is only managing keys with its content, all other stuff (like comments) is ignored.
