### ISSUE TITLE
High severity vulnerabilities on npm install

### ISSUE THREAD

**Issue by valleywood** [locize/locize-cli#85]
## 🐛 Bug Report

There are 2 high severity vulnerabilities reported on npm install this package.

npm audit report:

```
xlsx  *
Severity: high
Prototype Pollution in sheetJS - https://github.com/advisories/GHSA-4r6h-8v6p-xvw6
fix available via `npm audit fix --force`
Will install locize-cli@3.6.0, which is a breaking change
node_modules/xlsx
  locize-cli  >=3.7.0
  Depends on vulnerable versions of xlsx
  node_modules/locize-cli

2 high severity vulnerabilities
```

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

No vulnarabilities, at least npm audit fix should work.

```js
// Paste the expected results here
```

## Your Environment

runtime version: node 18.16.0; npm 8.3.1
module version: 7.14.4
os: Mac OS Monterray

**Comment by adrai** [comment]
v7.14.6 should address this
