### ISSUE TITLE
Support overwriting

### ISSUE THREAD

**Issue by thaindq** [locize/locize-cli#87]
## 🚀 Feature Proposal

Please support `overwrite` using cli, just like `copy-version`

## Motivation

Because it's faster and there is no modification cost
```
COPY TO is slower than OVERWRITE.
The changes cause modification costs.
```

## Example

```
locize overwrite latest --api-key my-api-key-d9de-4f55-9855-a9ef0ed44672 --project-id my-project-id-93e1-442a-ab35-24331fa294ba --ver production
```

or 

```
locize copy-version --overwrite latest --api-key my-api-key-d9de-4f55-9855-a9ef0ed44672 --project-id my-project-id-93e1-442a-ab35-24331fa294ba --ver production
```

**Comment by adrai** [comment]
The CLI uses this API endpoint: https://docs.locize.com/integration/api#copy-version
And it's the same behavior like [Overwriting](https://github.com/more/versioning#a-overwrite-with-data-from) via the UI.

**Comment by thaindq** [comment]
So you mean if I run
```locize copy-version latest --ver production```
It would be the same thing as using `Overwrite Version` (latest -> production) from the UI and would not cause modification costs?

**Comment by adrai** [comment]
yes

**Comment by thaindq** [comment]
Ok thank you for clarifying. I think you can improve the wording or update the cli docs to make it less confusing.
