### ISSUE TITLE
Sync command doesn't do what documentation says

### ISSUE THREAD

**Issue by megaturbo** [locize/locize-cli#90]
## 🐛 Bug Report

When using `locize-cli sync` it does not do what the documentation says.

According to documentation:

> if you have less keys (you have deleted some keys) in your local namespace it will remove them in locize too

But it doesn't remove them in locize.

> if you change the values of existing keys in the reference language, it will not change them in locize (to change the existing values you have to change it directly in locize or use the --update-values true argument)

But it does update them.

Am I doing something wrong ? I can give more information if necessary.

## To Reproduce

**Bug that doesn't remove key**

1. Set `en` as the reference language in the locize web app.
2. Manually remove a key from `en/translation.json`
3. Run `locize sync`
4. It does not remove the key in locize web app.

**Bug that update the keys**

1. Set `en` as the reference language in the locize web app.
2. Edit a value from `en/translation.json`
3. Run `locize sync`
4. It does update the value in locize web app.

## Expected behavior

I expect `locize sync` command to remove keys from my reference language.

I expect  `locize sync` command to *not* update values from my reference language.

## Your Environment

- *runtime version*: node 18, running locize through `yarn dlx locize`.
- *module version*: locize-cli@7.14.14
- *os*: Ubuntu 22.04.1
- I used a locize Admin api key that I set as environment variables.
- I'm currently using the trial period of locize

**Comment by adrai** [comment]
I just tried to reproduce both use cases, but they behave exactly as they should.
Can you please provide more information?
If you add the --dry true argument, you see what the CLI would do without actually doing it.
You can also write us an email to support@locize.com with the exact command line arguments you are using etc...

**Comment by megaturbo** [comment]
Thanks for the very fast answer. I can answer here for now.

I previously set my project id and api key through:
```bash
export LOCIZE_PROJECTID=<project_id>​
export LOCIZE_API_KEY=<api_key>​
```

The command I run is:

```bash
yarn dlx locize-cli sync --path public/locales
```

### Dry run example

I remove the `about` key in my `public/locales/en/translation.json` file. If I run

```bash
> yarn dlx locize-cli sync --path public/locales --dry true

checking remote (locize)...
checking local (<project_dir>/public/locales) only reference language...
calculate diffs...
adding 206 keys in en/translation...
would add key1, key2, key3,... in en/translation...
syncing...
FINISHED
```

So, now I indeed have 206 keys, and it does not show `about` in the list of keys to update. However it does not remove it on my web app (without the `--dry true`)

Should it output something about removal when using `--dry true` ?

**Comment by adrai** [comment]
I assume the version settings in your locize project (I assume 'latest') is not set to auto-publish mode, but to manual publish mode....
If you tell me the project-id (please via email), I can check that.
btw: https://github.com/locize/locize-cli?tab=readme-ov-file#synchronize-locize-with-your-repository-or-any-other-local-directory
<img width="814" alt="image" src="https://github.com/locize/locize-cli/assets/1086194/d7f5c30b-10e0-4ef0-8640-1c2a068fe481">

**Comment by megaturbo** [comment]
For posterity: It was a bug introduced by a previous release, which was [quickly fixed](https://github.com/locize/locize-cli/releases/tag/v7.14.15).

Thanks, closing.
