### ISSUE TITLE
Download command misses newly added namespaces for tenant projects

### ISSUE THREAD

**Issue by thaindq** [locize/locize-cli#91]
## 🐛 Bug Report

Download command misses newly added namespaces for tenant projects for languages other than the main language

## To Reproduce

- Create a project with 2 languages (for example `en` (main one) & `fr`)
- Create a tenant project
- Add a new namespace to the main project and add some tranlsations
- Execute download command with the tenant project id: `locize download --ver latest`
- The new namespace (json file) would appear in `en` directory but not in `fr`)

## Expected behavior

The new namespace (json file) should appear in both `en` & `fr` directories. It works correctly when running download command against the main project.

## Your Environment

- *runtime version*: node v18
- *locize-cli version*: 7.15.1

**Comment by adrai** [comment]
Hi there...
In case you added also content/translations for `fr` if was not able to reproduce it.

In case there was no content/translations for `fr`:
If the namespace in a particular language is empty it's the normal behaviour, that no file is created when downloading. This is not directly related to the tenant structure.
With v7.15.2 you can try the --skip-empty false argument => `locize download --skip-empty false`

Let me know if this information helps. If not, please provide more information to support@locize.com

**Comment by thaindq** [comment]
> slations for `fr` if was not able to reproduce it.
> 
> In case there was no content/translations for `fr`:

Hi, it's the first case. I've sent an email with additional info.

**Comment by thaindq** [comment]
The issue has been resolved. From support team:
>It was an issue with the combination of using tenants with the automatic machine translation feature. If a target language was never edited manually (only with MT) this could happen.
>This has been fixed now. So as soon as you change any key in that namespace it should work again.
