### ISSUE TITLE
Unexpected token '??=' with Node 14

### ISSUE THREAD

**Issue by Endikaorve** [locize/locize-cli#95]
## 💥 Regression Report

Since yesterday, running the following command:
`npx locize-cli download --format json --path <PATH> --api-key <API_KEY> --project-id <PROJECT_ID>`

is producing the following error:
`Unexpected token '??='`

More info:

After installing locize-cli and running: `locize`, this is the error:

```
.../locize-cli/node_modules/undici/lib/core/util.js:623

  const listeners = (obj[kListeners] ??= [])

SyntaxError: Unexpected token '??='
```

## Last working version

Worked up to version: 8.0.1

Stopped working in version: 8.0.1

## To Reproduce

Having Node v14.21.3
Run: `npx locize-cli download --format json --path <PATH> --api-key <API_KEY> --project-id <PROJECT_ID>`

## Expected behavior

The correct download of translations

## Your Environment

- *runtime version*: Node v14
- *os*: Linux

**Comment by adrai** [comment]
1. Node v14 is outdated
2. We don't use undici, but node-fetch here
3. Not reproducible

**Comment by Endikaorve** [comment]
Here is the dependency with `undici`:

```
─┬ android-string-resource@2.3.9
  └─┬ rdotjson@1.0.4
    └─┬ cheerio@1.0.0
      └── undici@6.19.7 
```

And it should be easily reproducible. It happens every time you run the command with Node version 14.

**Comment by adrai** [comment]
Like said Node.js v14 is end of life since April 30, 2023
and seems cheerio v1.0.0 requires at least Node.js v18.17
There's not much we can do here....
Alternatively, use the locize-cli binary: https://github.com/locize/locize-cli/releases

**Comment by adrai** [comment]
v8.0.2 should address this
