### ISSUE TITLE
Proposal: --language should support more than 1 language

### ISSUE THREAD

**Issue by RobertLiuMTL** [locize/locize-cli#96]
## 🚀 Feature Proposal

When running `locize sync`, we can pass an arg `--language`, the target language.

I believe it would be useful if locize-cli supported more than 1 language ! (or perhaps a new option `--languages: string[]`, or maybe `--excluded: string[]`). This would give users more flexibility.

## Motivation

Where I work, Locize.app is used by the translation team to translate the keys (A mix of human translations and AI translations).
Every week, we download the new changes to the main codebase. There, adjustments are made if necessary (EG: translation errors, shortening some text to fit our various screens, etc). Once the changes are done, in the code, everything is sync back to Locize.

Every week, we need to sync back about 12 languages. Because those languages are AI-translated, this is the end of the process for them.
We have other languages, those translated by professionals, that must not be sync back to Locize, because we have a different process for controlling its quality.

Right now, we are using a work around:
```
languages.forEach((language) => {
   locize sync --language ${language} --dry false
})
```

It would be cleaner if we could simply indicate the languages we want to sync back (or it could also be an array of languages to be excluded)

## Example

```
locize sync --languages cs,da,id,ja,nl,pl... --dry false

```

**Comment by adrai** [comment]
Good idea 👍

Your wish is my command ;-) try v8.1.0

**Comment by RobertLiuMTL** [comment]
> Good idea 👍
> 
> Your wish is my command ;-) try v8.1.0

That was quick :D

Thanks, I'll test it right away ^^

**Comment by RobertLiuMTL** [comment]
@adrai Tested and it works :) 
Thanks!
