### ISSUE TITLE
throw new Error('Expected an Agent instance as the first argument');

### ISSUE THREAD

**Issue by xuoutput** [locize/locize-cli#97]
## 🐛 Bug Report

run `locize sync --api-key xxxx --project-id xxxx --path ./app/i18n/locales`

`throw new Error('Expected an Agent instance as the first argument');`

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: v20.11.0
- *module version*:"locize-cli": "^8.1.1",
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
sorry, I'm not able to reproduce it.
Can you please share more information?
Are you using the binary? Or are you using the npm version? Which Node.js version do you use?
Please provide more information.
